/**
 * CNH pure-math parity with the Python reference `depz_sensor_sdk.vl53l8.cnh`.
 * The hex vectors below were produced by running the Python implementation
 * (CnhConfig.pack(), required_memory(), min_max_distance_mm(), bin_center_mm(),
 * max_bins(), decode()) — see the comments on each case.
 */

import { describe, expect, it } from "vitest";
import { CnhConfig, decode, maxBins } from "../src/sensors/vl53l8/cnh.js";

function toHex(data: Uint8Array): string {
  let s = "";
  for (const b of data) s += b.toString(16).padStart(2, "0");
  return s;
}

function fromHex(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.substring(i * 2, i * 2 + 2), 16);
  return out;
}

// python: c.init_config(0, 24, 4); c.create_agg_map(64, 0, 0, 2, 2, 4, 4)
const PACK_A =
  "000000000000000000000000000000000000041810010000003f01000000010102020303000001010202030304040505060607070404050506060707080809090a0a0b0b080809090a0a0b0b0c0c0d0d0e0e0f0f0c0c0d0d0e0e0f0f00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

// python: c.init_config(2, 18, 2); c.create_agg_map(16, 1, 1, 1, 1, 2, 2)
const PACK_B =
  "001000000000000000000000000000000000021204010000003f0100ffffffffff0001ffff0203ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

// python: c.init_config(1, 32, 1); c.create_agg_map(64, 0, 0, 4, 4, 2, 2)
const PACK_C =
  "000800000000000000000000000000000000012004010000003f01000000000001010101000000000101010100000000010101010000000001010101020202020303030302020202030303030202020203030303020202020303030300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

describe("vl53l8 cnh (parity with python reference)", () => {
  it("config A: pack/requiredMemory/minMax/binCenter", () => {
    const c = new CnhConfig();
    c.initConfig(0, 24, 4);
    c.createAggMap(64, 0, 0, 2, 2, 4, 4);
    expect(toHex(c.pack())).toBe(PACK_A);
    expect(c.pack().length).toBe(156);
    expect(c.requiredMemory()).toBe(2028);
    expect(c.minMaxDistanceMm()).toEqual([262, 3340]);
    expect(c.binCenterMm(0)).toBeCloseTo(75.0696, 10);
    expect(c.binCenterMm(5)).toBeCloseTo(825.7656, 10);
  });

  it("config B: pack/requiredMemory/minMax/binCenter", () => {
    const c = new CnhConfig();
    c.initConfig(2, 18, 2);
    c.createAggMap(16, 1, 1, 1, 1, 2, 2);
    expect(toHex(c.pack())).toBe(PACK_B);
    expect(c.requiredMemory()).toBe(408);
    expect(c.minMaxDistanceMm()).toEqual([300, 1201]);
    expect(c.binCenterMm(0)).toBeCloseTo(112.6044, 10);
    expect(c.binCenterMm(5)).toBeCloseTo(487.95239999999995, 10);
  });

  it("config C: pack/requiredMemory/minMax/binCenter", () => {
    const c = new CnhConfig();
    c.initConfig(1, 32, 1);
    c.createAggMap(64, 0, 0, 4, 4, 2, 2);
    expect(toHex(c.pack())).toBe(PACK_C);
    expect(c.requiredMemory()).toBe(688);
    expect(c.minMaxDistanceMm()).toEqual([243, 1032]);
    expect(c.binCenterMm(0)).toBeCloseTo(56.3022, 10);
    expect(c.binCenterMm(5)).toBeCloseTo(243.97619999999998, 10);
  });

  it("maxBins matches python max_bins", () => {
    expect(maxBins(16)).toBe(75);
    expect(maxBins(64)).toBe(18);
    expect(maxBins(4)).toBe(305);
  });

  it("decode matches the python-decoded synthetic block", () => {
    // Config: init_config(0, 3, 4); create_agg_map(64, 0, 0, 4, 4, 2, 1)
    // → nb_of_aggregates=2, feature_length=3, required_memory()=72.
    // Raw block + expected output generated by the python implementation.
    const c = new CnhConfig();
    c.initConfig(0, 3, 4);
    c.createAggMap(64, 0, 0, 4, 4, 2, 1);
    expect(c.nbOfAggregates).toBe(2);
    expect(c.featureLength).toBe(3);
    expect(c.requiredMemory()).toBe(72);
    const raw = fromHex(
      "010000000000000000100000100000000000000000000000000000006400000038ffffff2c010000a00f0000f4010000a8fdffff0102ff000301000020030000c0f9ffff02fe0000",
    );
    const out = decode(c, raw);
    expect(out.refResidual).toBe(2.0);
    expect(out.aggregates).toHaveLength(2);
    expect(out.aggregates[0]).toEqual({
      hist: [50.0, -50.0, 600.0],
      histRaw: [100, -200, 300],
      histScaler: [1, 2, -1],
      ambient: 200.0,
    });
    expect(out.aggregates[1]).toEqual({
      hist: [4000.0, 62.5, -300.0],
      histRaw: [4000, 500, -600],
      histScaler: [0, 3, 1],
      ambient: -6400.0,
    });
  });
});
