#!/usr/bin/env python3
"""Generate src/io/vl53l8_blobs.c from the Python SDK's VL53L8/L5/L7 blob data
(packages/depz-sensor-sdk-python/depz_sensor_sdk/vl53l8/data), the single
source of truth for the sensor firmware and configuration blobs (the TS SDK's
gen-vl53l8-assets.mjs reads the same files).

Three firmwares (cx = VL53L8CX ULD 2.1.0, ch = VL53LMZ ULD 2.0.16 also used by
l7ch, l7cx = VL53L5CX/L7CX ULD 2.0.1), four default configurations, and the
xtalk / NVM-command blobs every set shares. Stdlib only.

Run from packages/depz-sensor-sdk-c:  python3 scripts/gen_vl53l8_blobs.py
     --check: fail when the committed file is stale.
"""
import importlib.util
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
ULD = HERE.parent / "depz-sensor-sdk-python" / "depz_sensor_sdk" / "vl53l8" / "uld.py"
DATA = ULD.parent / "data"
OUT = HERE / "src" / "io" / "vl53l8_blobs.c"

BLOBS = [
    ("depz_vl53l8_fw_cx", "cx/firmware.bin"),
    ("depz_vl53l8_fw_ch", "ch/firmware.bin"),
    ("depz_vl53l8_fw_l7cx", "l7cx/firmware.bin"),
    ("depz_vl53l8_cfg_cx", "cx/default_configuration.bin"),
    ("depz_vl53l8_cfg_ch", "ch/default_configuration.bin"),
    ("depz_vl53l8_cfg_l7cx", "l7cx/default_configuration.bin"),
    ("depz_vl53l8_cfg_l7ch", "l7ch/default_configuration.bin"),
    ("depz_vl53l8_default_xtalk", "cx/default_xtalk.bin"),
    ("depz_vl53l8_get_nvm_cmd", "cx/get_nvm_cmd.bin"),
]
# The ST command tables the ULD writes verbatim (vl53l8cx_plugin_xtalk.h and
# friends), taken from uld.py so the two ports can never drift apart.
TABLES = [
    ("depz_vl53l8_get_xtalk_cmd", "GET_XTALK_CMD"),
    ("depz_vl53l8_calibrate_xtalk_cx", "CALIBRATE_XTALK"),
    ("depz_vl53l8_calibrate_xtalk_lmz", "CALIBRATE_XTALK_LMZ"),
    ("depz_vl53l8_calibrate_xtalk_l7cx", "CALIBRATE_XTALK_L7CX"),
]
# Blobs the sets share (the generator refuses to run if that stops being true).
SHARED = [("cx/default_xtalk.bin", "ch/default_xtalk.bin"), ("cx/get_nvm_cmd.bin", "ch/get_nvm_cmd.bin")]


def render() -> str:
    for a, b in SHARED:
        if (DATA / a).read_bytes() != (DATA / b).read_bytes():
            raise SystemExit(f"{a} and {b} differ: store both")
    out = [
        "/* vl53l8_blobs.c — GENERATED by scripts/gen_vl53l8_blobs.py from the Python",
        " * SDK's vl53l8/data; do not edit. ST sensor firmware and configuration",
        " * blobs (VL53L8CX ULD 2.1.0, VL53LMZ ULD 2.0.16, VL53L5CX/L7CX ULD 2.0.1),",
        " * redistributed under ST's BSD-3-Clause licence. */",
        '#include "vl53l8_blobs.h"',
        "",
    ]
    spec = importlib.util.spec_from_file_location("uld", ULD)
    uld = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(uld)
    items = [(name, rel, (DATA / rel).read_bytes()) for name, rel in BLOBS]
    items += [(name, f"uld.py {attr}", getattr(uld, attr)) for name, attr in TABLES]
    for name, src, data in items:
        out.append(f"/* {src} */")
        out.append(f"const size_t {name}_len = {len(data)};")
        out.append(f"const uint8_t {name}[{len(data)}] = {{")
        for i in range(0, len(data), 20):
            out.append("    " + ",".join(f"0x{b:02X}" for b in data[i:i + 20]) + ",")
        out.append("};")
        out.append("")
    return "\n".join(out)


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"{OUT.name} is stale: run scripts/gen_vl53l8_blobs.py")
            return 1
        print(f"{OUT.name} up to date")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
