#!/usr/bin/env python3
"""Generate src/io/vl53lx_bare_tables.{h,c} from the Python SDK's histogram
driver tables (packages/depz-sensor-sdk-python/depz_sensor_sdk/vl53lx/uld/bare/
regs.py and tuning.py), the single source of truth for them.

regs.py: every register block of ST's BareDriver image with its field list
(offset, width, signedness, the C codec's mask) — here one struct per block,
fields as int64_t (the Python image stores whatever is assigned and clips only
on encode), plus the decode / encode that keep the reserved holes byte-exact.
tuning.py: TUNING (the tuning-parameter struct after init) and DEFAULTS (the
raw header) as #defines.

Run from packages/depz-sensor-sdk-c:  python3 scripts/gen_vl53lx_bare_tables.py
     --check: fail when the committed files are stale.
"""
import importlib.util
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
BARE = HERE.parent / "depz-sensor-sdk-python" / "depz_sensor_sdk" / "vl53lx" / "uld" / "bare"
OUT_H = HERE / "src" / "io" / "vl53lx_bare_tables.h"
OUT_C = HERE / "src" / "io" / "vl53lx_bare_tables.c"


def _load(name):
    spec = importlib.util.spec_from_file_location(name, BARE / f"{name}.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def render():
    regs = _load("regs")
    tuning = _load("tuning")
    blocks = list(regs.BLOCKS.items())
    h = [
        "/* vl53lx_bare_tables.h — GENERATED by scripts/gen_vl53lx_bare_tables.py from",
        " * the Python SDK's vl53lx/uld/bare/regs.py and tuning.py; do not edit. The",
        " * register blocks of ST's VL53LX BareDriver image and its tuning parameters. */",
        "#ifndef DEPZ_VL53LX_BARE_TABLES_H",
        "#define DEPZ_VL53LX_BARE_TABLES_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "typedef enum {",
    ]
    for i, (name, _b) in enumerate(blocks):
        h.append(f"    VLXB_BLK_{name.upper()} = {i},")
    h += [f"    VLXB_BLK_COUNT = {len(blocks)}", "} vlxb_block_id;", ""]
    for name, b in blocks:
        h.append(f"/* {name}: 0x{b.base:04X}, {b.size} bytes */")
        h.append("typedef struct {")
        h.append(f"    uint8_t raw[{b.size}]; /* the bytes last decoded: reserved holes */")
        for f in b.fields:
            h.append(f"    int64_t {f.name};")
        h.append(f"}} vlxb_{name};")
        h.append("")
    h.append("/* The whole device image, one member per block. */")
    h.append("typedef struct {")
    for name, _b in blocks:
        h.append(f"    vlxb_{name} {name};")
    h += ["} vlxb_image;", ""]
    h += [
        "typedef struct { uint16_t base; uint16_t size; int writable; } vlxb_block_geom;",
        "extern const vlxb_block_geom vlxb_blocks[VLXB_BLK_COUNT];",
        "/* raw -> fields (raw has the block's size). */",
        "void vlxb_decode(vlxb_image *img, vlxb_block_id id, const uint8_t *raw);",
        "/* fields -> bytes, masked and clipped as the C codec does. */",
        "void vlxb_encode(const vlxb_image *img, vlxb_block_id id, uint8_t *out);",
        "",
        "/* TUNING: VL53LX_tuning_parm_storage_t after init. */",
    ]
    for k, v in tuning.TUNING.items():
        h.append(f"#define VLXB_{k.upper()} ({v})")
    h.append("")
    h.append("/* DEFAULTS: the tuning header's raw defines. */")
    for k, v in tuning.DEFAULTS.items():
        h.append(f"#define VLXB_{k} ({v})")
    h += ["", "#endif /* DEPZ_VL53LX_BARE_TABLES_H */", ""]

    c = [
        "/* vl53lx_bare_tables.c — GENERATED by scripts/gen_vl53lx_bare_tables.py from",
        " * the Python SDK's vl53lx/uld/bare/regs.py; do not edit. */",
        '#include "vl53lx_bare_tables.h"',
        "",
        "#include <string.h>",
        "",
        "const vlxb_block_geom vlxb_blocks[VLXB_BLK_COUNT] = {",
    ]
    for name, b in blocks:
        c.append(f"    {{0x{b.base:04X}, {b.size}, {1 if b.writable else 0}}}, /* {name} */")
    c += ["};", ""]
    c += [
        "static int64_t get_be(const uint8_t *p, int width, uint64_t mask, int is_signed)",
        "{",
        "    uint64_t v = 0;",
        "    int k, bits = width * 8;",
        "    for (k = 0; k < width; k++) v = (v << 8) | p[k];",
        "    v &= mask;",
        "    if (is_signed && v >= ((uint64_t)1 << (bits - 1))) return (int64_t)v - ((int64_t)1 << bits);",
        "    return (int64_t)v;",
        "}",
        "",
        "static void put_be(uint8_t *p, int width, uint64_t mask, int64_t value)",
        "{",
        "    uint64_t v = (uint64_t)value & mask;",
        "    int k;",
        "    if (width < 8) v &= ((uint64_t)1 << (width * 8)) - 1;",
        "    for (k = width - 1; k >= 0; k--) {",
        "        p[k] = (uint8_t)v;",
        "        v >>= 8;",
        "    }",
        "}",
        "",
        "void vlxb_decode(vlxb_image *img, vlxb_block_id id, const uint8_t *raw)",
        "{",
        "    switch (id) {",
    ]
    for name, b in blocks:
        c.append(f"    case VLXB_BLK_{name.upper()}: {{")
        c.append(f"        vlxb_{name} *s = &img->{name};")
        c.append(f"        memcpy(s->raw, raw, {b.size});")
        for f in b.fields:
            mask = f.mask if f.mask is not None else (1 << (8 * f.width)) - 1
            c.append(f"        s->{f.name} = get_be(raw + {f.off}, {f.width}, 0x{mask:X}u, {1 if f.signed else 0});")
        c.append("        break;")
        c.append("    }")
    c += ["    default:", "        break;", "    }", "}", "",
          "void vlxb_encode(const vlxb_image *img, vlxb_block_id id, uint8_t *out)",
          "{", "    switch (id) {"]
    for name, b in blocks:
        c.append(f"    case VLXB_BLK_{name.upper()}: {{")
        c.append(f"        const vlxb_{name} *s = &img->{name};")
        c.append(f"        memcpy(out, s->raw, {b.size});")
        for f in b.fields:
            mask = f.mask if f.mask is not None else (1 << (8 * f.width)) - 1
            c.append(f"        put_be(out + {f.off}, {f.width}, 0x{mask:X}u, s->{f.name});")
        c.append("        break;")
        c.append("    }")
    c += ["    default:", "        break;", "    }", "}", ""]
    return "\n".join(h), "\n".join(c)


def main() -> int:
    h, c = render()
    if "--check" in sys.argv:
        stale = [p.name for p, t in ((OUT_H, h), (OUT_C, c)) if not p.exists() or p.read_text() != t]
        if stale:
            print("stale (run scripts/gen_vl53lx_bare_tables.py): " + ", ".join(stale))
            return 1
        return 0
    OUT_H.write_text(h)
    OUT_C.write_text(c)
    return 0


if __name__ == "__main__":
    sys.exit(main())
