/**
 * uld/bare/tuning — ST's tuning parameters, as the BareDriver ships them.
 * Mirror of the Python `depz_sensor_sdk.vl53lx.uld.bare.tuning` (generated
 * from it — data, do not edit by hand).
 *
 * The preset modes read initial phases, timeouts, DSS targets and sigma
 * thresholds out of `VL53LX_tuning_parm_storage_t`, which
 * `VL53LX_init_tuning_parm_storage_struct()` fills from a header of 187
 * defines. `TUNING` is that struct after initialisation, keyed by the C field
 * name; `DEFAULTS` is the raw header, for the parameters the histogram
 * post-processing reads directly without a `tp_` field of their own.
 */

export const TUNING: Readonly<Record<string, number>> = {
  tp_tuning_parm_version: 30, // TUNINGPARM_VERSION_DEFAULT
  tp_tuning_parm_key_table_version: 14, // TUNINGPARM_KEY_TABLE_VERSION_DEFAULT
  tp_tuning_parm_lld_version: 12180, // TUNINGPARM_LLD_VERSION_DEFAULT
  tp_init_phase_rtn_lite_long: 14, // TUNINGPARM_INITIAL_PHASE_RTN_LITE_LONG_RANGE_DEFAULT
  tp_init_phase_rtn_lite_med: 10, // TUNINGPARM_INITIAL_PHASE_RTN_LITE_MED_RANGE_DEFAULT
  tp_init_phase_rtn_lite_short: 6, // TUNINGPARM_INITIAL_PHASE_RTN_LITE_SHORT_RANGE_DEFAULT
  tp_init_phase_ref_lite_long: 14, // TUNINGPARM_INITIAL_PHASE_REF_LITE_LONG_RANGE_DEFAULT
  tp_init_phase_ref_lite_med: 10, // TUNINGPARM_INITIAL_PHASE_REF_LITE_MED_RANGE_DEFAULT
  tp_init_phase_ref_lite_short: 6, // TUNINGPARM_INITIAL_PHASE_REF_LITE_SHORT_RANGE_DEFAULT
  tp_init_phase_rtn_hist_long: 9, // TUNINGPARM_INITIAL_PHASE_RTN_HISTO_LONG_RANGE_DEFAULT
  tp_init_phase_rtn_hist_med: 5, // TUNINGPARM_INITIAL_PHASE_RTN_HISTO_MED_RANGE_DEFAULT
  tp_init_phase_rtn_hist_short: 3, // TUNINGPARM_INITIAL_PHASE_RTN_HISTO_SHORT_RANGE_DEFAULT
  tp_init_phase_ref_hist_long: 6, // TUNINGPARM_INITIAL_PHASE_REF_HISTO_LONG_RANGE_DEFAULT
  tp_init_phase_ref_hist_med: 6, // TUNINGPARM_INITIAL_PHASE_REF_HISTO_MED_RANGE_DEFAULT
  tp_init_phase_ref_hist_short: 6, // TUNINGPARM_INITIAL_PHASE_REF_HISTO_SHORT_RANGE_DEFAULT
  tp_consistency_lite_phase_tolerance: 2, // TUNINGPARM_CONSISTENCY_LITE_PHASE_TOLERANCE_DEFAULT
  tp_phasecal_target: 33, // TUNINGPARM_PHASECAL_TARGET_DEFAULT
  tp_cal_repeat_rate: 0, // TUNINGPARM_LITE_CAL_REPEAT_RATE_DEFAULT
  tp_lite_min_clip: 0, // TUNINGPARM_LITE_MIN_CLIP_MM_DEFAULT
  tp_lite_long_sigma_thresh_mm: 60, // TUNINGPARM_LITE_LONG_SIGMA_THRESH_MM_DEFAULT
  tp_lite_med_sigma_thresh_mm: 60, // TUNINGPARM_LITE_MED_SIGMA_THRESH_MM_DEFAULT
  tp_lite_short_sigma_thresh_mm: 60, // TUNINGPARM_LITE_SHORT_SIGMA_THRESH_MM_DEFAULT
  tp_lite_long_min_count_rate_rtn_mcps: 128, // TUNINGPARM_LITE_LONG_MIN_COUNT_RATE_RTN_MCPS_DEFAULT
  tp_lite_med_min_count_rate_rtn_mcps: 128, // TUNINGPARM_LITE_MED_MIN_COUNT_RATE_RTN_MCPS_DEFAULT
  tp_lite_short_min_count_rate_rtn_mcps: 128, // TUNINGPARM_LITE_SHORT_MIN_COUNT_RATE_RTN_MCPS_DEFAULT
  tp_lite_sigma_est_pulse_width_ns: 8, // TUNINGPARM_LITE_SIGMA_EST_PULSE_WIDTH_DEFAULT
  tp_lite_sigma_est_amb_width_ns: 16, // TUNINGPARM_LITE_SIGMA_EST_AMB_WIDTH_NS_DEFAULT
  tp_lite_sigma_ref_mm: 1, // TUNINGPARM_LITE_SIGMA_REF_MM_DEFAULT
  tp_lite_seed_cfg: 2, // TUNINGPARM_LITE_SEED_CONFIG_DEFAULT
  tp_timed_seed_cfg: 1, // TUNINGPARM_TIMED_SEED_CONFIG_DEFAULT
  tp_lite_quantifier: 2, // TUNINGPARM_LITE_QUANTIFIER_DEFAULT
  tp_lite_first_order_select: 0, // TUNINGPARM_LITE_FIRST_ORDER_SELECT_DEFAULT
  tp_uwr_enable: 1, // TUNINGPARM_UWR_ENABLE_DEFAULT
  tp_uwr_med_z_1_min: 2000, // TUNINGPARM_UWR_MEDIUM_ZONE_1_MIN_DEFAULT
  tp_uwr_med_z_1_max: 2750, // TUNINGPARM_UWR_MEDIUM_ZONE_1_MAX_DEFAULT
  tp_uwr_med_z_2_min: 250, // TUNINGPARM_UWR_MEDIUM_ZONE_2_MIN_DEFAULT
  tp_uwr_med_z_2_max: 1000, // TUNINGPARM_UWR_MEDIUM_ZONE_2_MAX_DEFAULT
  tp_uwr_med_z_3_min: 1250, // TUNINGPARM_UWR_MEDIUM_ZONE_3_MIN_DEFAULT
  tp_uwr_med_z_3_max: 1750, // TUNINGPARM_UWR_MEDIUM_ZONE_3_MAX_DEFAULT
  tp_uwr_med_z_4_min: 1250, // TUNINGPARM_UWR_MEDIUM_ZONE_4_MIN_DEFAULT
  tp_uwr_med_z_4_max: 1750, // TUNINGPARM_UWR_MEDIUM_ZONE_4_MAX_DEFAULT
  tp_uwr_med_z_5_min: -200, // TUNINGPARM_UWR_MEDIUM_ZONE_5_MIN_DEFAULT
  tp_uwr_med_z_5_max: 200, // TUNINGPARM_UWR_MEDIUM_ZONE_5_MAX_DEFAULT
  tp_uwr_med_corr_z_1_rangea: 2300, // TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_1_RANGEA_DEFAULT
  tp_uwr_med_corr_z_1_rangeb: 0, // TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_1_RANGEB_DEFAULT
  tp_uwr_med_corr_z_2_rangea: 2300, // TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_2_RANGEA_DEFAULT
  tp_uwr_med_corr_z_2_rangeb: 3050, // TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_2_RANGEB_DEFAULT
  tp_uwr_med_corr_z_3_rangea: 4600, // TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_3_RANGEA_DEFAULT
  tp_uwr_med_corr_z_3_rangeb: 3050, // TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_3_RANGEB_DEFAULT
  tp_uwr_med_corr_z_4_rangea: 4600, // TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_4_RANGEA_DEFAULT
  tp_uwr_med_corr_z_4_rangeb: 6200, // TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_4_RANGEB_DEFAULT
  tp_uwr_med_corr_z_5_rangea: 0, // TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_5_RANGEA_DEFAULT
  tp_uwr_med_corr_z_5_rangeb: 0, // TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_5_RANGEB_DEFAULT
  tp_uwr_lng_z_1_min: 250, // TUNINGPARM_UWR_LONG_ZONE_1_MIN_DEFAULT
  tp_uwr_lng_z_1_max: 1250, // TUNINGPARM_UWR_LONG_ZONE_1_MAX_DEFAULT
  tp_uwr_lng_z_2_min: 3250, // TUNINGPARM_UWR_LONG_ZONE_2_MIN_DEFAULT
  tp_uwr_lng_z_2_max: 4500, // TUNINGPARM_UWR_LONG_ZONE_2_MAX_DEFAULT
  tp_uwr_lng_z_3_min: -200, // TUNINGPARM_UWR_LONG_ZONE_3_MIN_DEFAULT
  tp_uwr_lng_z_3_max: 200, // TUNINGPARM_UWR_LONG_ZONE_3_MAX_DEFAULT
  tp_uwr_lng_z_4_min: 0, // TUNINGPARM_UWR_LONG_ZONE_4_MIN_DEFAULT
  tp_uwr_lng_z_4_max: 0, // TUNINGPARM_UWR_LONG_ZONE_4_MAX_DEFAULT
  tp_uwr_lng_z_5_min: 0, // TUNINGPARM_UWR_LONG_ZONE_5_MIN_DEFAULT
  tp_uwr_lng_z_5_max: 0, // TUNINGPARM_UWR_LONG_ZONE_5_MAX_DEFAULT
  tp_uwr_lng_corr_z_1_rangea: 3850, // TUNINGPARM_UWR_LONG_CORRECTION_ZONE_1_RANGEA_DEFAULT
  tp_uwr_lng_corr_z_1_rangeb: 4600, // TUNINGPARM_UWR_LONG_CORRECTION_ZONE_1_RANGEB_DEFAULT
  tp_uwr_lng_corr_z_2_rangea: 3850, // TUNINGPARM_UWR_LONG_CORRECTION_ZONE_2_RANGEA_DEFAULT
  tp_uwr_lng_corr_z_2_rangeb: 0, // TUNINGPARM_UWR_LONG_CORRECTION_ZONE_2_RANGEB_DEFAULT
  tp_uwr_lng_corr_z_3_rangea: 0, // TUNINGPARM_UWR_LONG_CORRECTION_ZONE_3_RANGEA_DEFAULT
  tp_uwr_lng_corr_z_3_rangeb: 0, // TUNINGPARM_UWR_LONG_CORRECTION_ZONE_3_RANGEB_DEFAULT
  tp_uwr_lng_corr_z_4_rangea: 0, // TUNINGPARM_UWR_LONG_CORRECTION_ZONE_4_RANGEA_DEFAULT
  tp_uwr_lng_corr_z_4_rangeb: 0, // TUNINGPARM_UWR_LONG_CORRECTION_ZONE_4_RANGEB_DEFAULT
  tp_uwr_lng_corr_z_5_rangea: 0, // TUNINGPARM_UWR_LONG_CORRECTION_ZONE_5_RANGEA_DEFAULT
  tp_uwr_lng_corr_z_5_rangeb: 0, // TUNINGPARM_UWR_LONG_CORRECTION_ZONE_5_RANGEB_DEFAULT
  tp_dss_target_lite_mcps: 2560, // TUNINGPARM_LITE_DSS_CONFIG_TARGET_TOTAL_RATE_MCPS_DEFAULT
  tp_dss_target_histo_mcps: 5120, // TUNINGPARM_RANGING_DSS_CONFIG_TARGET_TOTAL_RATE_MCPS_DEFAULT
  tp_dss_target_histo_mz_mcps: 5120, // TUNINGPARM_MZ_DSS_CONFIG_TARGET_TOTAL_RATE_MCPS_DEFAULT
  tp_dss_target_timed_mcps: 2560, // TUNINGPARM_TIMED_DSS_CONFIG_TARGET_TOTAL_RATE_MCPS_DEFAULT
  tp_phasecal_timeout_lite_us: 1000, // TUNINGPARM_LITE_PHASECAL_CONFIG_TIMEOUT_US_DEFAULT
  tp_phasecal_timeout_hist_long_us: 15000, // TUNINGPARM_RANGING_LONG_PHASECAL_CONFIG_TIMEOUT_US_DEFAULT
  tp_phasecal_timeout_hist_med_us: 9000, // TUNINGPARM_RANGING_MED_PHASECAL_CONFIG_TIMEOUT_US_DEFAULT
  tp_phasecal_timeout_hist_short_us: 6000, // TUNINGPARM_RANGING_SHORT_PHASECAL_CONFIG_TIMEOUT_US_DEFAULT
  tp_phasecal_timeout_mz_long_us: 15000, // TUNINGPARM_MZ_LONG_PHASECAL_CONFIG_TIMEOUT_US_DEFAULT
  tp_phasecal_timeout_mz_med_us: 9000, // TUNINGPARM_MZ_MED_PHASECAL_CONFIG_TIMEOUT_US_DEFAULT
  tp_phasecal_timeout_mz_short_us: 6000, // TUNINGPARM_MZ_SHORT_PHASECAL_CONFIG_TIMEOUT_US_DEFAULT
  tp_phasecal_timeout_timed_us: 1000, // TUNINGPARM_TIMED_PHASECAL_CONFIG_TIMEOUT_US_DEFAULT
  tp_mm_timeout_lite_us: 2000, // TUNINGPARM_LITE_MM_CONFIG_TIMEOUT_US_DEFAULT
  tp_mm_timeout_histo_us: 2000, // TUNINGPARM_RANGING_MM_CONFIG_TIMEOUT_US_DEFAULT
  tp_mm_timeout_mz_us: 2000, // TUNINGPARM_MZ_MM_CONFIG_TIMEOUT_US_DEFAULT
  tp_mm_timeout_timed_us: 2000, // TUNINGPARM_TIMED_MM_CONFIG_TIMEOUT_US_DEFAULT
  tp_range_timeout_lite_us: 63000, // TUNINGPARM_LITE_RANGE_CONFIG_TIMEOUT_US_DEFAULT
  tp_range_timeout_histo_us: 2500, // TUNINGPARM_RANGING_RANGE_CONFIG_TIMEOUT_US_DEFAULT
  tp_range_timeout_mz_us: 2500, // TUNINGPARM_MZ_RANGE_CONFIG_TIMEOUT_US_DEFAULT
  tp_range_timeout_timed_us: 13000, // TUNINGPARM_TIMED_RANGE_CONFIG_TIMEOUT_US_DEFAULT
  tp_mm_timeout_lpa_us: 1, // TUNINGPARM_LOWPOWERAUTO_MM_CONFIG_TIMEOUT_US_DEFAULT
  tp_range_timeout_lpa_us: 8000, // TUNINGPARM_LOWPOWERAUTO_RANGE_CONFIG_TIMEOUT_US_DEFAULT
  tp_dss_target_very_short_mcps: 10240, // TUNINGPARM_VERY_SHORT_DSS_RATE_MCPS_DEFAULT
  tp_phasecal_patch_power: 0, // TUNINGPARM_PHASECAL_PATCH_POWER_DEFAULT
  tp_hist_merge: 1, // TUNINGPARM_HIST_MERGE_DEFAULT
  tp_reset_merge_threshold: 15000, // TUNINGPARM_RESET_MERGE_THRESHOLD_DEFAULT
  tp_hist_merge_max_size: 6, // TUNINGPARM_HIST_MERGE_MAX_SIZE_DEFAULT
};

export const DEFAULTS: Readonly<Record<string, number>> = {
  TUNINGPARM_CONSISTENCY_HIST_EVENT_SIGMA_DEFAULT: 0,
  TUNINGPARM_CONSISTENCY_HIST_EVENT_SIGMA_MIN_SPAD_LIMIT_DEFAULT: 2048,
  TUNINGPARM_CONSISTENCY_HIST_MIN_MAX_TOLERANCE_MM_DEFAULT: 0,
  TUNINGPARM_CONSISTENCY_HIST_PHASE_TOLERANCE_DEFAULT: 8,
  TUNINGPARM_CONSISTENCY_LITE_PHASE_TOLERANCE_DEFAULT: 2,
  TUNINGPARM_DMAX_CFG_REFLECTANCE_ARRAY_0_DEFAULT: 15,
  TUNINGPARM_DMAX_CFG_REFLECTANCE_ARRAY_1_DEFAULT: 52,
  TUNINGPARM_DMAX_CFG_REFLECTANCE_ARRAY_2_DEFAULT: 200,
  TUNINGPARM_DMAX_CFG_REFLECTANCE_ARRAY_3_DEFAULT: 364,
  TUNINGPARM_DMAX_CFG_REFLECTANCE_ARRAY_4_DEFAULT: 400,
  TUNINGPARM_DMAX_CFG_SIGNAL_THRESH_SIGMA_DEFAULT: 32,
  TUNINGPARM_DYNXTALK_AVERAGED_XTALK_DELTA_DEFAULT: 308,
  TUNINGPARM_DYNXTALK_CLIP_LIMIT_DEFAULT: 10240,
  TUNINGPARM_DYNXTALK_MAX_SMUDGE_FACTOR_DEFAULT: 2000,
  TUNINGPARM_DYNXTALK_NODETECT_AMB_THRESHOLD_KCPS_DEFAULT: 57671680,
  TUNINGPARM_DYNXTALK_NODETECT_MIN_RANGE_MM_DEFAULT: 900,
  TUNINGPARM_DYNXTALK_NODETECT_SAMPLE_LIMIT_DEFAULT: 40,
  TUNINGPARM_DYNXTALK_NODETECT_XTALK_OFFSET_KCPS_DEFAULT: 410,
  TUNINGPARM_DYNXTALK_NOISE_MARGIN_DEFAULT: 100,
  TUNINGPARM_DYNXTALK_SAMPLE_LIMIT_DEFAULT: 200,
  TUNINGPARM_DYNXTALK_SCALER_CALC_METHOD_DEFAULT: 0,
  TUNINGPARM_DYNXTALK_SINGLE_XTALK_DELTA_DEFAULT: 2048,
  TUNINGPARM_DYNXTALK_SMUDGE_COR_SINGLE_APPLY_DEFAULT: 0,
  TUNINGPARM_DYNXTALK_SMUDGE_MARGIN_DEFAULT: 0,
  TUNINGPARM_DYNXTALK_USER_SCALER_SET_DEFAULT: 0,
  TUNINGPARM_DYNXTALK_XGRADIENT_SCALER_DEFAULT: 256,
  TUNINGPARM_DYNXTALK_XTALK_AMB_THRESHOLD_DEFAULT: 128,
  TUNINGPARM_DYNXTALK_XTALK_OFFSET_LIMIT_DEFAULT: 0,
  TUNINGPARM_DYNXTALK_XTALK_OFFSET_LIMIT_HI_DEFAULT: 0,
  TUNINGPARM_DYNXTALK_YGRADIENT_SCALER_DEFAULT: 256,
  TUNINGPARM_HIST_ALGO_SELECT_DEFAULT: 4,
  TUNINGPARM_HIST_AMB_EST_METHOD_DEFAULT: 1,
  TUNINGPARM_HIST_AMB_EVENTS_SCALER_DEFAULT: 4157,
  TUNINGPARM_HIST_AMB_THRESH_SIGMA_0_DEFAULT: 80,
  TUNINGPARM_HIST_AMB_THRESH_SIGMA_1_DEFAULT: 100,
  TUNINGPARM_HIST_FILTER_WOI_0_DEFAULT: 1,
  TUNINGPARM_HIST_FILTER_WOI_1_DEFAULT: 2,
  TUNINGPARM_HIST_GAIN_FACTOR_DEFAULT: 1987,
  TUNINGPARM_HIST_MERGE_DEFAULT: 1,
  TUNINGPARM_HIST_MERGE_MAX_SIZE_DEFAULT: 6,
  TUNINGPARM_HIST_MIN_AMB_THRESH_EVENTS_DEFAULT: 16,
  TUNINGPARM_HIST_NOISE_THRESHOLD_DEFAULT: 50,
  TUNINGPARM_HIST_SIGMA_EST_REF_MM_DEFAULT: 1,
  TUNINGPARM_HIST_SIGMA_THRESH_MM_DEFAULT: 180,
  TUNINGPARM_HIST_SIGNAL_TOTAL_EVENTS_LIMIT_DEFAULT: 100,
  TUNINGPARM_HIST_TARGET_ORDER_DEFAULT: 1,
  TUNINGPARM_HIST_XTALK_MARGIN_KCPS_DEFAULT: 0,
  TUNINGPARM_INITIAL_PHASE_REF_HISTO_LONG_RANGE_DEFAULT: 6,
  TUNINGPARM_INITIAL_PHASE_REF_HISTO_MED_RANGE_DEFAULT: 6,
  TUNINGPARM_INITIAL_PHASE_REF_HISTO_SHORT_RANGE_DEFAULT: 6,
  TUNINGPARM_INITIAL_PHASE_REF_LITE_LONG_RANGE_DEFAULT: 14,
  TUNINGPARM_INITIAL_PHASE_REF_LITE_MED_RANGE_DEFAULT: 10,
  TUNINGPARM_INITIAL_PHASE_REF_LITE_SHORT_RANGE_DEFAULT: 6,
  TUNINGPARM_INITIAL_PHASE_RTN_HISTO_LONG_RANGE_DEFAULT: 9,
  TUNINGPARM_INITIAL_PHASE_RTN_HISTO_MED_RANGE_DEFAULT: 5,
  TUNINGPARM_INITIAL_PHASE_RTN_HISTO_SHORT_RANGE_DEFAULT: 3,
  TUNINGPARM_INITIAL_PHASE_RTN_LITE_LONG_RANGE_DEFAULT: 14,
  TUNINGPARM_INITIAL_PHASE_RTN_LITE_MED_RANGE_DEFAULT: 10,
  TUNINGPARM_INITIAL_PHASE_RTN_LITE_SHORT_RANGE_DEFAULT: 6,
  TUNINGPARM_KEY_TABLE_VERSION_DEFAULT: 14,
  TUNINGPARM_LITE_CAL_REPEAT_RATE_DEFAULT: 0,
  TUNINGPARM_LITE_DSS_CONFIG_TARGET_TOTAL_RATE_MCPS_DEFAULT: 2560,
  TUNINGPARM_LITE_FIRST_ORDER_SELECT_DEFAULT: 0,
  TUNINGPARM_LITE_LONG_MIN_COUNT_RATE_RTN_MCPS_DEFAULT: 128,
  TUNINGPARM_LITE_LONG_SIGMA_THRESH_MM_DEFAULT: 60,
  TUNINGPARM_LITE_MED_MIN_COUNT_RATE_RTN_MCPS_DEFAULT: 128,
  TUNINGPARM_LITE_MED_SIGMA_THRESH_MM_DEFAULT: 60,
  TUNINGPARM_LITE_MIN_CLIP_MM_DEFAULT: 0,
  TUNINGPARM_LITE_MM_CONFIG_TIMEOUT_US_DEFAULT: 2000,
  TUNINGPARM_LITE_PHASECAL_CONFIG_TIMEOUT_US_DEFAULT: 1000,
  TUNINGPARM_LITE_QUANTIFIER_DEFAULT: 2,
  TUNINGPARM_LITE_RANGE_CONFIG_TIMEOUT_US_DEFAULT: 63000,
  TUNINGPARM_LITE_RANGING_GAIN_FACTOR_DEFAULT: 2011,
  TUNINGPARM_LITE_RIT_MULT_DEFAULT: 64,
  TUNINGPARM_LITE_SEED_CONFIG_DEFAULT: 2,
  TUNINGPARM_LITE_SHORT_MIN_COUNT_RATE_RTN_MCPS_DEFAULT: 128,
  TUNINGPARM_LITE_SHORT_SIGMA_THRESH_MM_DEFAULT: 60,
  TUNINGPARM_LITE_SIGMA_EST_AMB_WIDTH_NS_DEFAULT: 16,
  TUNINGPARM_LITE_SIGMA_EST_PULSE_WIDTH_DEFAULT: 8,
  TUNINGPARM_LITE_SIGMA_REF_MM_DEFAULT: 1,
  TUNINGPARM_LITE_XTALK_MARGIN_KCPS_DEFAULT: 0,
  TUNINGPARM_LLD_VERSION_DEFAULT: 12180,
  TUNINGPARM_LOWPOWERAUTO_MM_CONFIG_TIMEOUT_US_DEFAULT: 1,
  TUNINGPARM_LOWPOWERAUTO_RANGE_CONFIG_TIMEOUT_US_DEFAULT: 8000,
  TUNINGPARM_LOWPOWERAUTO_VHV_LOOP_BOUND_DEFAULT: 3,
  TUNINGPARM_MZ_DSS_CONFIG_TARGET_TOTAL_RATE_MCPS_DEFAULT: 5120,
  TUNINGPARM_MZ_LONG_PHASECAL_CONFIG_TIMEOUT_US_DEFAULT: 15000,
  TUNINGPARM_MZ_MED_PHASECAL_CONFIG_TIMEOUT_US_DEFAULT: 9000,
  TUNINGPARM_MZ_MM_CONFIG_TIMEOUT_US_DEFAULT: 2000,
  TUNINGPARM_MZ_RANGE_CONFIG_TIMEOUT_US_DEFAULT: 2500,
  TUNINGPARM_MZ_SHORT_PHASECAL_CONFIG_TIMEOUT_US_DEFAULT: 6000,
  TUNINGPARM_OFFSET_CAL_DSS_RATE_MCPS_DEFAULT: 2560,
  TUNINGPARM_OFFSET_CAL_MM1_SAMPLES_DEFAULT: 40,
  TUNINGPARM_OFFSET_CAL_MM2_SAMPLES_DEFAULT: 9,
  TUNINGPARM_OFFSET_CAL_MM_TIMEOUT_US_DEFAULT: 13000,
  TUNINGPARM_OFFSET_CAL_PHASECAL_TIMEOUT_US_DEFAULT: 15000,
  TUNINGPARM_OFFSET_CAL_PRE_SAMPLES_DEFAULT: 8,
  TUNINGPARM_OFFSET_CAL_RANGE_TIMEOUT_US_DEFAULT: 13000,
  TUNINGPARM_PHASECAL_PATCH_POWER_DEFAULT: 0,
  TUNINGPARM_PHASECAL_TARGET_DEFAULT: 33,
  TUNINGPARM_RANGING_DSS_CONFIG_TARGET_TOTAL_RATE_MCPS_DEFAULT: 5120,
  TUNINGPARM_RANGING_LONG_PHASECAL_CONFIG_TIMEOUT_US_DEFAULT: 15000,
  TUNINGPARM_RANGING_MED_PHASECAL_CONFIG_TIMEOUT_US_DEFAULT: 9000,
  TUNINGPARM_RANGING_MM_CONFIG_TIMEOUT_US_DEFAULT: 2000,
  TUNINGPARM_RANGING_RANGE_CONFIG_TIMEOUT_US_DEFAULT: 2500,
  TUNINGPARM_RANGING_SHORT_PHASECAL_CONFIG_TIMEOUT_US_DEFAULT: 6000,
  TUNINGPARM_REFSPADCHAR_DEVICE_TEST_MODE_DEFAULT: 8,
  TUNINGPARM_REFSPADCHAR_MAX_COUNTRATE_LIMIT_MCPS_DEFAULT: 5120,
  TUNINGPARM_REFSPADCHAR_MIN_COUNTRATE_LIMIT_MCPS_DEFAULT: 1280,
  TUNINGPARM_REFSPADCHAR_PHASECAL_TIMEOUT_US_DEFAULT: 1000,
  TUNINGPARM_REFSPADCHAR_TARGET_COUNT_RATE_MCPS_DEFAULT: 2560,
  TUNINGPARM_REFSPADCHAR_VCSEL_PERIOD_DEFAULT: 11,
  TUNINGPARM_RESET_MERGE_THRESHOLD_DEFAULT: 15000,
  TUNINGPARM_SPADMAP_RATE_LIMIT_MCPS_DEFAULT: 12,
  TUNINGPARM_SPADMAP_VCSEL_PERIOD_DEFAULT: 18,
  TUNINGPARM_SPADMAP_VCSEL_START_DEFAULT: 15,
  TUNINGPARM_TIMED_DSS_CONFIG_TARGET_TOTAL_RATE_MCPS_DEFAULT: 2560,
  TUNINGPARM_TIMED_MM_CONFIG_TIMEOUT_US_DEFAULT: 2000,
  TUNINGPARM_TIMED_PHASECAL_CONFIG_TIMEOUT_US_DEFAULT: 1000,
  TUNINGPARM_TIMED_RANGE_CONFIG_TIMEOUT_US_DEFAULT: 13000,
  TUNINGPARM_TIMED_SEED_CONFIG_DEFAULT: 1,
  TUNINGPARM_UWR_ENABLE_DEFAULT: 1,
  TUNINGPARM_UWR_LONG_CORRECTION_ZONE_1_RANGEA_DEFAULT: 3850,
  TUNINGPARM_UWR_LONG_CORRECTION_ZONE_1_RANGEB_DEFAULT: 4600,
  TUNINGPARM_UWR_LONG_CORRECTION_ZONE_2_RANGEA_DEFAULT: 3850,
  TUNINGPARM_UWR_LONG_CORRECTION_ZONE_2_RANGEB_DEFAULT: 0,
  TUNINGPARM_UWR_LONG_CORRECTION_ZONE_3_RANGEA_DEFAULT: 0,
  TUNINGPARM_UWR_LONG_CORRECTION_ZONE_3_RANGEB_DEFAULT: 0,
  TUNINGPARM_UWR_LONG_CORRECTION_ZONE_4_RANGEA_DEFAULT: 0,
  TUNINGPARM_UWR_LONG_CORRECTION_ZONE_4_RANGEB_DEFAULT: 0,
  TUNINGPARM_UWR_LONG_CORRECTION_ZONE_5_RANGEA_DEFAULT: 0,
  TUNINGPARM_UWR_LONG_CORRECTION_ZONE_5_RANGEB_DEFAULT: 0,
  TUNINGPARM_UWR_LONG_ZONE_1_MAX_DEFAULT: 1250,
  TUNINGPARM_UWR_LONG_ZONE_1_MIN_DEFAULT: 250,
  TUNINGPARM_UWR_LONG_ZONE_2_MAX_DEFAULT: 4500,
  TUNINGPARM_UWR_LONG_ZONE_2_MIN_DEFAULT: 3250,
  TUNINGPARM_UWR_LONG_ZONE_3_MAX_DEFAULT: 200,
  TUNINGPARM_UWR_LONG_ZONE_3_MIN_DEFAULT: -200,
  TUNINGPARM_UWR_LONG_ZONE_4_MAX_DEFAULT: 0,
  TUNINGPARM_UWR_LONG_ZONE_4_MIN_DEFAULT: 0,
  TUNINGPARM_UWR_LONG_ZONE_5_MAX_DEFAULT: 0,
  TUNINGPARM_UWR_LONG_ZONE_5_MIN_DEFAULT: 0,
  TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_1_RANGEA_DEFAULT: 2300,
  TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_1_RANGEB_DEFAULT: 0,
  TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_2_RANGEA_DEFAULT: 2300,
  TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_2_RANGEB_DEFAULT: 3050,
  TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_3_RANGEA_DEFAULT: 4600,
  TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_3_RANGEB_DEFAULT: 3050,
  TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_4_RANGEA_DEFAULT: 4600,
  TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_4_RANGEB_DEFAULT: 6200,
  TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_5_RANGEA_DEFAULT: 0,
  TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_5_RANGEB_DEFAULT: 0,
  TUNINGPARM_UWR_MEDIUM_ZONE_1_MAX_DEFAULT: 2750,
  TUNINGPARM_UWR_MEDIUM_ZONE_1_MIN_DEFAULT: 2000,
  TUNINGPARM_UWR_MEDIUM_ZONE_2_MAX_DEFAULT: 1000,
  TUNINGPARM_UWR_MEDIUM_ZONE_2_MIN_DEFAULT: 250,
  TUNINGPARM_UWR_MEDIUM_ZONE_3_MAX_DEFAULT: 1750,
  TUNINGPARM_UWR_MEDIUM_ZONE_3_MIN_DEFAULT: 1250,
  TUNINGPARM_UWR_MEDIUM_ZONE_4_MAX_DEFAULT: 1750,
  TUNINGPARM_UWR_MEDIUM_ZONE_4_MIN_DEFAULT: 1250,
  TUNINGPARM_UWR_MEDIUM_ZONE_5_MAX_DEFAULT: 200,
  TUNINGPARM_UWR_MEDIUM_ZONE_5_MIN_DEFAULT: -200,
  TUNINGPARM_VERSION_DEFAULT: 30,
  TUNINGPARM_VERY_SHORT_DSS_RATE_MCPS_DEFAULT: 10240,
  TUNINGPARM_VHV_LOOPBOUND_DEFAULT: 129,
  TUNINGPARM_XTALK_DETECT_EVENT_SIGMA_DEFAULT: 80,
  TUNINGPARM_XTALK_DETECT_MAX_SIGMA_MM_DEFAULT: 140,
  TUNINGPARM_XTALK_DETECT_MAX_VALID_RANGE_MM_DEFAULT: 50,
  TUNINGPARM_XTALK_DETECT_MAX_VALID_RATE_KCPS_DEFAULT: 400,
  TUNINGPARM_XTALK_DETECT_MIN_MAX_TOLERANCE_DEFAULT: 50,
  TUNINGPARM_XTALK_DETECT_MIN_VALID_RANGE_MM_DEFAULT: -50,
  TUNINGPARM_XTALK_EXTRACT_BIN_TIMEOUT_US_DEFAULT: 10000,
  TUNINGPARM_XTALK_EXTRACT_DSS_RATE_MCPS_DEFAULT: 5120,
  TUNINGPARM_XTALK_EXTRACT_DSS_TIMEOUT_US_DEFAULT: 2000,
  TUNINGPARM_XTALK_EXTRACT_MAX_FILTER_THRESH_MM_DEFAULT: 70,
  TUNINGPARM_XTALK_EXTRACT_MAX_VALID_RATE_KCPS_DEFAULT: 640,
  TUNINGPARM_XTALK_EXTRACT_MIN_FILTER_THRESH_MM_DEFAULT: -70,
  TUNINGPARM_XTALK_EXTRACT_NUM_OF_SAMPLES_DEFAULT: 7,
  TUNINGPARM_XTALK_EXTRACT_PHASECAL_TIMEOUT_US_DEFAULT: 15000,
  TUNINGPARM_XTALK_EXTRACT_SIGMA_THRESHOLD_MM_DEFAULT: 140,
  TUNINGPARM_ZONE_CAL_DSS_RATE_MCPS_DEFAULT: 5120,
  TUNINGPARM_ZONE_CAL_DSS_TIMEOUT_US_DEFAULT: 2000,
  TUNINGPARM_ZONE_CAL_PHASECAL_NUM_SAMPLES_DEFAULT: 16,
  TUNINGPARM_ZONE_CAL_PHASECAL_TIMEOUT_US_DEFAULT: 15000,
  TUNINGPARM_ZONE_CAL_RANGE_TIMEOUT_US_DEFAULT: 1000,
  TUNINGPARM_ZONE_CAL_ZONE_NUM_SAMPLES_DEFAULT: 8,
};
