/**
 * Golden consumer for `usb_ids.json` (the (vid,pid)→{known,model} table and
 * the serial-ordering rule shared with the Python SDK). The vectors are owned
 * & regenerated by the Python agent; this file asserts byte-for-byte parity on
 * the identity table and the port-ordering logic.
 */

import { describe, expect, it } from "vitest";
import {
  isKnownDepzUsb,
  orderPortsBySerial,
  usbModelHint,
  type DepzPortInfo,
} from "../../src/index.js";
import { loadVectors } from "./vectors.js";

const VECTOR_FILE = "usb_ids.json";

interface IdentityCase {
  vid: number;
  pid: number;
  known: boolean;
  model: string | null;
}
interface OrderingCase {
  name: string;
  ports: { port: string; serial: string | null }[];
  order: string[];
}
interface UsbVectors {
  vid: number;
  dev_vid: number;
  dev_pid: number;
  pid_range: [number, number];
  identity: IdentityCase[];
  serial_ordering: OrderingCase[];
}

const data = loadVectors<UsbVectors>(VECTOR_FILE);

describe("usb_ids identity table", () => {
  for (const c of data.identity) {
    it(`0x${c.vid.toString(16)}:0x${c.pid.toString(16)} known=${c.known} model=${c.model}`, () => {
      expect(isKnownDepzUsb(c.vid, c.pid)).toBe(c.known);
      expect(usbModelHint(c.vid, c.pid)).toBe(c.model);
    });
  }
});

describe("usb_ids serial-ordering cases", () => {
  for (const oc of data.serial_ordering) {
    it(oc.name, () => {
      const ports: DepzPortInfo[] = oc.ports.map((p) => ({
        path: p.port,
        serialNumber: p.serial ?? undefined,
      }));
      expect(orderPortsBySerial(ports).map((p) => p.path)).toEqual(oc.order);
    });
  }
});
