/* vl53lx_bare_tables.h — GENERATED by scripts/gen_vl53lx_bare_tables.py from
 * the Python SDK's vl53lx/uld/bare/regs.py and tuning.py; do not edit. The
 * register blocks of ST's VL53LX BareDriver image and its tuning parameters. */
#ifndef DEPZ_VL53LX_BARE_TABLES_H
#define DEPZ_VL53LX_BARE_TABLES_H

#include <stddef.h>
#include <stdint.h>

typedef enum {
    VLXB_BLK_STATIC_NVM_MANAGED = 0,
    VLXB_BLK_CUSTOMER_NVM_MANAGED = 1,
    VLXB_BLK_STATIC_CONFIG = 2,
    VLXB_BLK_GENERAL_CONFIG = 3,
    VLXB_BLK_TIMING_CONFIG = 4,
    VLXB_BLK_DYNAMIC_CONFIG = 5,
    VLXB_BLK_SYSTEM_CONTROL = 6,
    VLXB_BLK_SYSTEM_RESULTS = 7,
    VLXB_BLK_CORE_RESULTS = 8,
    VLXB_BLK_DEBUG_RESULTS = 9,
    VLXB_BLK_NVM_COPY_DATA = 10,
    VLXB_BLK_PATCH_DEBUG = 11,
    VLXB_BLK_GPH_GENERAL_CONFIG = 12,
    VLXB_BLK_GPH_STATIC_CONFIG = 13,
    VLXB_BLK_GPH_TIMING_CONFIG = 14,
    VLXB_BLK_FW_INTERNAL = 15,
    VLXB_BLK_COUNT = 16
} vlxb_block_id;

/* static_nvm_managed: 0x0001, 11 bytes */
typedef struct {
    uint8_t raw[11]; /* the bytes last decoded: reserved holes */
    int64_t i2c_slave__device_address;
    int64_t ana_config__vhv_ref_sel_vddpix;
    int64_t ana_config__vhv_ref_sel_vquench;
    int64_t ana_config__reg_avdd1v2_sel;
    int64_t ana_config__fast_osc__trim;
    int64_t osc_measured__fast_osc__frequency;
    int64_t vhv_config__timeout_macrop_loop_bound;
    int64_t vhv_config__count_thresh;
    int64_t vhv_config__offset;
    int64_t vhv_config__init;
} vlxb_static_nvm_managed;

/* customer_nvm_managed: 0x000D, 23 bytes */
typedef struct {
    uint8_t raw[23]; /* the bytes last decoded: reserved holes */
    int64_t global_config__spad_enables_ref_0;
    int64_t global_config__spad_enables_ref_1;
    int64_t global_config__spad_enables_ref_2;
    int64_t global_config__spad_enables_ref_3;
    int64_t global_config__spad_enables_ref_4;
    int64_t global_config__spad_enables_ref_5;
    int64_t global_config__ref_en_start_select;
    int64_t ref_spad_man__num_requested_ref_spads;
    int64_t ref_spad_man__ref_location;
    int64_t algo__crosstalk_compensation_plane_offset_kcps;
    int64_t algo__crosstalk_compensation_x_plane_gradient_kcps;
    int64_t algo__crosstalk_compensation_y_plane_gradient_kcps;
    int64_t ref_spad_char__total_rate_target_mcps;
    int64_t algo__part_to_part_range_offset_mm;
    int64_t mm_config__inner_offset_mm;
    int64_t mm_config__outer_offset_mm;
} vlxb_customer_nvm_managed;

/* static_config: 0x0024, 32 bytes */
typedef struct {
    uint8_t raw[32]; /* the bytes last decoded: reserved holes */
    int64_t dss_config__target_total_rate_mcps;
    int64_t debug__ctrl;
    int64_t test_mode__ctrl;
    int64_t clk_gating__ctrl;
    int64_t nvm_bist__ctrl;
    int64_t nvm_bist__num_nvm_words;
    int64_t nvm_bist__start_address;
    int64_t host_if__status;
    int64_t pad_i2c_hv__config;
    int64_t pad_i2c_hv__extsup_config;
    int64_t gpio_hv_pad__ctrl;
    int64_t gpio_hv_mux__ctrl;
    int64_t gpio__tio_hv_status;
    int64_t gpio__fio_hv_status;
    int64_t ana_config__spad_sel_pswidth;
    int64_t ana_config__vcsel_pulse_width_offset;
    int64_t ana_config__fast_osc__config_ctrl;
    int64_t sigma_estimator__effective_pulse_width_ns;
    int64_t sigma_estimator__effective_ambient_width_ns;
    int64_t sigma_estimator__sigma_ref_mm;
    int64_t algo__crosstalk_compensation_valid_height_mm;
    int64_t spare_host_config__static_config_spare_0;
    int64_t spare_host_config__static_config_spare_1;
    int64_t algo__range_ignore_threshold_mcps;
    int64_t algo__range_ignore_valid_height_mm;
    int64_t algo__range_min_clip;
    int64_t algo__consistency_check__tolerance;
    int64_t spare_host_config__static_config_spare_2;
    int64_t sd_config__reset_stages_msb;
    int64_t sd_config__reset_stages_lsb;
} vlxb_static_config;

/* general_config: 0x0044, 22 bytes */
typedef struct {
    uint8_t raw[22]; /* the bytes last decoded: reserved holes */
    int64_t gph_config__stream_count_update_value;
    int64_t global_config__stream_divider;
    int64_t system__interrupt_config_gpio;
    int64_t cal_config__vcsel_start;
    int64_t cal_config__repeat_rate;
    int64_t global_config__vcsel_width;
    int64_t phasecal_config__timeout_macrop;
    int64_t phasecal_config__target;
    int64_t phasecal_config__override;
    int64_t dss_config__roi_mode_control;
    int64_t system__thresh_rate_high;
    int64_t system__thresh_rate_low;
    int64_t dss_config__manual_effective_spads_select;
    int64_t dss_config__manual_block_select;
    int64_t dss_config__aperture_attenuation;
    int64_t dss_config__max_spads_limit;
    int64_t dss_config__min_spads_limit;
} vlxb_general_config;

/* timing_config: 0x005A, 23 bytes */
typedef struct {
    uint8_t raw[23]; /* the bytes last decoded: reserved holes */
    int64_t mm_config__timeout_macrop_a_hi;
    int64_t mm_config__timeout_macrop_a_lo;
    int64_t mm_config__timeout_macrop_b_hi;
    int64_t mm_config__timeout_macrop_b_lo;
    int64_t range_config__timeout_macrop_a_hi;
    int64_t range_config__timeout_macrop_a_lo;
    int64_t range_config__vcsel_period_a;
    int64_t range_config__timeout_macrop_b_hi;
    int64_t range_config__timeout_macrop_b_lo;
    int64_t range_config__vcsel_period_b;
    int64_t range_config__sigma_thresh;
    int64_t range_config__min_count_rate_rtn_limit_mcps;
    int64_t range_config__valid_phase_low;
    int64_t range_config__valid_phase_high;
    int64_t system__intermeasurement_period;
    int64_t system__fractional_enable;
} vlxb_timing_config;

/* dynamic_config: 0x0071, 18 bytes */
typedef struct {
    uint8_t raw[18]; /* the bytes last decoded: reserved holes */
    int64_t system__grouped_parameter_hold_0;
    int64_t system__thresh_high;
    int64_t system__thresh_low;
    int64_t system__enable_xtalk_per_quadrant;
    int64_t system__seed_config;
    int64_t sd_config__woi_sd0;
    int64_t sd_config__woi_sd1;
    int64_t sd_config__initial_phase_sd0;
    int64_t sd_config__initial_phase_sd1;
    int64_t system__grouped_parameter_hold_1;
    int64_t sd_config__first_order_select;
    int64_t sd_config__quantifier;
    int64_t roi_config__user_roi_centre_spad;
    int64_t roi_config__user_roi_requested_global_xy_size;
    int64_t system__sequence_config;
    int64_t system__grouped_parameter_hold;
} vlxb_dynamic_config;

/* system_control: 0x0083, 5 bytes */
typedef struct {
    uint8_t raw[5]; /* the bytes last decoded: reserved holes */
    int64_t power_management__go1_power_force;
    int64_t system__stream_count_ctrl;
    int64_t firmware__enable;
    int64_t system__interrupt_clear;
    int64_t system__mode_start;
} vlxb_system_control;

/* system_results: 0x0088, 44 bytes */
typedef struct {
    uint8_t raw[44]; /* the bytes last decoded: reserved holes */
    int64_t result__interrupt_status;
    int64_t result__range_status;
    int64_t result__report_status;
    int64_t result__stream_count;
    int64_t result__dss_actual_effective_spads_sd0;
    int64_t result__peak_signal_count_rate_mcps_sd0;
    int64_t result__ambient_count_rate_mcps_sd0;
    int64_t result__sigma_sd0;
    int64_t result__phase_sd0;
    int64_t result__final_crosstalk_corrected_range_mm_sd0;
    int64_t result__peak_signal_count_rate_crosstalk_corrected_mcps_sd0;
    int64_t result__mm_inner_actual_effective_spads_sd0;
    int64_t result__mm_outer_actual_effective_spads_sd0;
    int64_t result__avg_signal_count_rate_mcps_sd0;
    int64_t result__dss_actual_effective_spads_sd1;
    int64_t result__peak_signal_count_rate_mcps_sd1;
    int64_t result__ambient_count_rate_mcps_sd1;
    int64_t result__sigma_sd1;
    int64_t result__phase_sd1;
    int64_t result__final_crosstalk_corrected_range_mm_sd1;
    int64_t result__spare_0_sd1;
    int64_t result__spare_1_sd1;
    int64_t result__spare_2_sd1;
    int64_t result__spare_3_sd1;
    int64_t result__thresh_info;
} vlxb_system_results;

/* core_results: 0x00B4, 33 bytes */
typedef struct {
    uint8_t raw[33]; /* the bytes last decoded: reserved holes */
    int64_t result_core__ambient_window_events_sd0;
    int64_t result_core__ranging_total_events_sd0;
    int64_t result_core__signal_total_events_sd0;
    int64_t result_core__total_periods_elapsed_sd0;
    int64_t result_core__ambient_window_events_sd1;
    int64_t result_core__ranging_total_events_sd1;
    int64_t result_core__signal_total_events_sd1;
    int64_t result_core__total_periods_elapsed_sd1;
    int64_t result_core__spare_0;
} vlxb_core_results;

/* debug_results: 0x00D6, 56 bytes */
typedef struct {
    uint8_t raw[56]; /* the bytes last decoded: reserved holes */
    int64_t phasecal_result__reference_phase;
    int64_t phasecal_result__vcsel_start;
    int64_t ref_spad_char_result__num_actual_ref_spads;
    int64_t ref_spad_char_result__ref_location;
    int64_t vhv_result__coldboot_status;
    int64_t vhv_result__search_result;
    int64_t vhv_result__latest_setting;
    int64_t result__osc_calibrate_val;
    int64_t ana_config__powerdown_go1;
    int64_t ana_config__ref_bg_ctrl;
    int64_t ana_config__regdvdd1v2_ctrl;
    int64_t ana_config__osc_slow_ctrl;
    int64_t test_mode__status;
    int64_t firmware__system_status;
    int64_t firmware__mode_status;
    int64_t firmware__secondary_mode_status;
    int64_t firmware__cal_repeat_rate_counter;
    int64_t gph__system__thresh_high;
    int64_t gph__system__thresh_low;
    int64_t gph__system__enable_xtalk_per_quadrant;
    int64_t gph__spare_0;
    int64_t gph__sd_config__woi_sd0;
    int64_t gph__sd_config__woi_sd1;
    int64_t gph__sd_config__initial_phase_sd0;
    int64_t gph__sd_config__initial_phase_sd1;
    int64_t gph__sd_config__first_order_select;
    int64_t gph__sd_config__quantifier;
    int64_t gph__roi_config__user_roi_centre_spad;
    int64_t gph__roi_config__user_roi_requested_global_xy_size;
    int64_t gph__system__sequence_config;
    int64_t gph__gph_id;
    int64_t system__interrupt_set;
    int64_t interrupt_manager__enables;
    int64_t interrupt_manager__clear;
    int64_t interrupt_manager__status;
    int64_t mcu_to_host_bank__wr_access_en;
    int64_t power_management__go1_reset_status;
    int64_t pad_startup_mode__value_ro;
    int64_t pad_startup_mode__value_ctrl;
    int64_t pll_period_us;
    int64_t interrupt_scheduler__data_out;
    int64_t nvm_bist__complete;
    int64_t nvm_bist__status;
} vlxb_debug_results;

/* nvm_copy_data: 0x010F, 49 bytes */
typedef struct {
    uint8_t raw[49]; /* the bytes last decoded: reserved holes */
    int64_t identification__model_id;
    int64_t identification__module_type;
    int64_t identification__revision_id;
    int64_t identification__module_id;
    int64_t ana_config__fast_osc__trim_max;
    int64_t ana_config__fast_osc__freq_set;
    int64_t ana_config__vcsel_trim;
    int64_t ana_config__vcsel_selion;
    int64_t ana_config__vcsel_selion_max;
    int64_t protected_laser_safety__lock_bit;
    int64_t laser_safety__key;
    int64_t laser_safety__key_ro;
    int64_t laser_safety__clip;
    int64_t laser_safety__mult;
    int64_t global_config__spad_enables_rtn_0;
    int64_t global_config__spad_enables_rtn_1;
    int64_t global_config__spad_enables_rtn_2;
    int64_t global_config__spad_enables_rtn_3;
    int64_t global_config__spad_enables_rtn_4;
    int64_t global_config__spad_enables_rtn_5;
    int64_t global_config__spad_enables_rtn_6;
    int64_t global_config__spad_enables_rtn_7;
    int64_t global_config__spad_enables_rtn_8;
    int64_t global_config__spad_enables_rtn_9;
    int64_t global_config__spad_enables_rtn_10;
    int64_t global_config__spad_enables_rtn_11;
    int64_t global_config__spad_enables_rtn_12;
    int64_t global_config__spad_enables_rtn_13;
    int64_t global_config__spad_enables_rtn_14;
    int64_t global_config__spad_enables_rtn_15;
    int64_t global_config__spad_enables_rtn_16;
    int64_t global_config__spad_enables_rtn_17;
    int64_t global_config__spad_enables_rtn_18;
    int64_t global_config__spad_enables_rtn_19;
    int64_t global_config__spad_enables_rtn_20;
    int64_t global_config__spad_enables_rtn_21;
    int64_t global_config__spad_enables_rtn_22;
    int64_t global_config__spad_enables_rtn_23;
    int64_t global_config__spad_enables_rtn_24;
    int64_t global_config__spad_enables_rtn_25;
    int64_t global_config__spad_enables_rtn_26;
    int64_t global_config__spad_enables_rtn_27;
    int64_t global_config__spad_enables_rtn_28;
    int64_t global_config__spad_enables_rtn_29;
    int64_t global_config__spad_enables_rtn_30;
    int64_t global_config__spad_enables_rtn_31;
    int64_t roi_config__mode_roi_centre_spad;
    int64_t roi_config__mode_roi_xy_size;
} vlxb_nvm_copy_data;

/* patch_debug: 0x0F20, 2 bytes */
typedef struct {
    uint8_t raw[2]; /* the bytes last decoded: reserved holes */
    int64_t result__debug_status;
    int64_t result__debug_stage;
} vlxb_patch_debug;

/* gph_general_config: 0x0F24, 5 bytes */
typedef struct {
    uint8_t raw[5]; /* the bytes last decoded: reserved holes */
    int64_t gph__system__thresh_rate_high;
    int64_t gph__system__thresh_rate_low;
    int64_t gph__system__interrupt_config_gpio;
} vlxb_gph_general_config;

/* gph_static_config: 0x0F2F, 6 bytes */
typedef struct {
    uint8_t raw[6]; /* the bytes last decoded: reserved holes */
    int64_t gph__dss_config__roi_mode_control;
    int64_t gph__dss_config__manual_effective_spads_select;
    int64_t gph__dss_config__manual_block_select;
    int64_t gph__dss_config__max_spads_limit;
    int64_t gph__dss_config__min_spads_limit;
} vlxb_gph_static_config;

/* gph_timing_config: 0x0F36, 16 bytes */
typedef struct {
    uint8_t raw[16]; /* the bytes last decoded: reserved holes */
    int64_t gph__mm_config__timeout_macrop_a_hi;
    int64_t gph__mm_config__timeout_macrop_a_lo;
    int64_t gph__mm_config__timeout_macrop_b_hi;
    int64_t gph__mm_config__timeout_macrop_b_lo;
    int64_t gph__range_config__timeout_macrop_a_hi;
    int64_t gph__range_config__timeout_macrop_a_lo;
    int64_t gph__range_config__vcsel_period_a;
    int64_t gph__range_config__vcsel_period_b;
    int64_t gph__range_config__timeout_macrop_b_hi;
    int64_t gph__range_config__timeout_macrop_b_lo;
    int64_t gph__range_config__sigma_thresh;
    int64_t gph__range_config__min_count_rate_rtn_limit_mcps;
    int64_t gph__range_config__valid_phase_low;
    int64_t gph__range_config__valid_phase_high;
} vlxb_gph_timing_config;

/* fw_internal: 0x0F46, 2 bytes */
typedef struct {
    uint8_t raw[2]; /* the bytes last decoded: reserved holes */
    int64_t firmware__internal_stream_count_div;
    int64_t firmware__internal_stream_counter_val;
} vlxb_fw_internal;

/* The whole device image, one member per block. */
typedef struct {
    vlxb_static_nvm_managed static_nvm_managed;
    vlxb_customer_nvm_managed customer_nvm_managed;
    vlxb_static_config static_config;
    vlxb_general_config general_config;
    vlxb_timing_config timing_config;
    vlxb_dynamic_config dynamic_config;
    vlxb_system_control system_control;
    vlxb_system_results system_results;
    vlxb_core_results core_results;
    vlxb_debug_results debug_results;
    vlxb_nvm_copy_data nvm_copy_data;
    vlxb_patch_debug patch_debug;
    vlxb_gph_general_config gph_general_config;
    vlxb_gph_static_config gph_static_config;
    vlxb_gph_timing_config gph_timing_config;
    vlxb_fw_internal fw_internal;
} vlxb_image;

typedef struct { uint16_t base; uint16_t size; int writable; } vlxb_block_geom;
extern const vlxb_block_geom vlxb_blocks[VLXB_BLK_COUNT];
/* raw -> fields (raw has the block's size). */
void vlxb_decode(vlxb_image *img, vlxb_block_id id, const uint8_t *raw);
/* fields -> bytes, masked and clipped as the C codec does. */
void vlxb_encode(const vlxb_image *img, vlxb_block_id id, uint8_t *out);

/* TUNING: VL53LX_tuning_parm_storage_t after init. */
#define VLXB_TP_TUNING_PARM_VERSION (30)
#define VLXB_TP_TUNING_PARM_KEY_TABLE_VERSION (14)
#define VLXB_TP_TUNING_PARM_LLD_VERSION (12180)
#define VLXB_TP_INIT_PHASE_RTN_LITE_LONG (14)
#define VLXB_TP_INIT_PHASE_RTN_LITE_MED (10)
#define VLXB_TP_INIT_PHASE_RTN_LITE_SHORT (6)
#define VLXB_TP_INIT_PHASE_REF_LITE_LONG (14)
#define VLXB_TP_INIT_PHASE_REF_LITE_MED (10)
#define VLXB_TP_INIT_PHASE_REF_LITE_SHORT (6)
#define VLXB_TP_INIT_PHASE_RTN_HIST_LONG (9)
#define VLXB_TP_INIT_PHASE_RTN_HIST_MED (5)
#define VLXB_TP_INIT_PHASE_RTN_HIST_SHORT (3)
#define VLXB_TP_INIT_PHASE_REF_HIST_LONG (6)
#define VLXB_TP_INIT_PHASE_REF_HIST_MED (6)
#define VLXB_TP_INIT_PHASE_REF_HIST_SHORT (6)
#define VLXB_TP_CONSISTENCY_LITE_PHASE_TOLERANCE (2)
#define VLXB_TP_PHASECAL_TARGET (33)
#define VLXB_TP_CAL_REPEAT_RATE (0)
#define VLXB_TP_LITE_MIN_CLIP (0)
#define VLXB_TP_LITE_LONG_SIGMA_THRESH_MM (60)
#define VLXB_TP_LITE_MED_SIGMA_THRESH_MM (60)
#define VLXB_TP_LITE_SHORT_SIGMA_THRESH_MM (60)
#define VLXB_TP_LITE_LONG_MIN_COUNT_RATE_RTN_MCPS (128)
#define VLXB_TP_LITE_MED_MIN_COUNT_RATE_RTN_MCPS (128)
#define VLXB_TP_LITE_SHORT_MIN_COUNT_RATE_RTN_MCPS (128)
#define VLXB_TP_LITE_SIGMA_EST_PULSE_WIDTH_NS (8)
#define VLXB_TP_LITE_SIGMA_EST_AMB_WIDTH_NS (16)
#define VLXB_TP_LITE_SIGMA_REF_MM (1)
#define VLXB_TP_LITE_SEED_CFG (2)
#define VLXB_TP_TIMED_SEED_CFG (1)
#define VLXB_TP_LITE_QUANTIFIER (2)
#define VLXB_TP_LITE_FIRST_ORDER_SELECT (0)
#define VLXB_TP_UWR_ENABLE (1)
#define VLXB_TP_UWR_MED_Z_1_MIN (2000)
#define VLXB_TP_UWR_MED_Z_1_MAX (2750)
#define VLXB_TP_UWR_MED_Z_2_MIN (250)
#define VLXB_TP_UWR_MED_Z_2_MAX (1000)
#define VLXB_TP_UWR_MED_Z_3_MIN (1250)
#define VLXB_TP_UWR_MED_Z_3_MAX (1750)
#define VLXB_TP_UWR_MED_Z_4_MIN (1250)
#define VLXB_TP_UWR_MED_Z_4_MAX (1750)
#define VLXB_TP_UWR_MED_Z_5_MIN (-200)
#define VLXB_TP_UWR_MED_Z_5_MAX (200)
#define VLXB_TP_UWR_MED_CORR_Z_1_RANGEA (2300)
#define VLXB_TP_UWR_MED_CORR_Z_1_RANGEB (0)
#define VLXB_TP_UWR_MED_CORR_Z_2_RANGEA (2300)
#define VLXB_TP_UWR_MED_CORR_Z_2_RANGEB (3050)
#define VLXB_TP_UWR_MED_CORR_Z_3_RANGEA (4600)
#define VLXB_TP_UWR_MED_CORR_Z_3_RANGEB (3050)
#define VLXB_TP_UWR_MED_CORR_Z_4_RANGEA (4600)
#define VLXB_TP_UWR_MED_CORR_Z_4_RANGEB (6200)
#define VLXB_TP_UWR_MED_CORR_Z_5_RANGEA (0)
#define VLXB_TP_UWR_MED_CORR_Z_5_RANGEB (0)
#define VLXB_TP_UWR_LNG_Z_1_MIN (250)
#define VLXB_TP_UWR_LNG_Z_1_MAX (1250)
#define VLXB_TP_UWR_LNG_Z_2_MIN (3250)
#define VLXB_TP_UWR_LNG_Z_2_MAX (4500)
#define VLXB_TP_UWR_LNG_Z_3_MIN (-200)
#define VLXB_TP_UWR_LNG_Z_3_MAX (200)
#define VLXB_TP_UWR_LNG_Z_4_MIN (0)
#define VLXB_TP_UWR_LNG_Z_4_MAX (0)
#define VLXB_TP_UWR_LNG_Z_5_MIN (0)
#define VLXB_TP_UWR_LNG_Z_5_MAX (0)
#define VLXB_TP_UWR_LNG_CORR_Z_1_RANGEA (3850)
#define VLXB_TP_UWR_LNG_CORR_Z_1_RANGEB (4600)
#define VLXB_TP_UWR_LNG_CORR_Z_2_RANGEA (3850)
#define VLXB_TP_UWR_LNG_CORR_Z_2_RANGEB (0)
#define VLXB_TP_UWR_LNG_CORR_Z_3_RANGEA (0)
#define VLXB_TP_UWR_LNG_CORR_Z_3_RANGEB (0)
#define VLXB_TP_UWR_LNG_CORR_Z_4_RANGEA (0)
#define VLXB_TP_UWR_LNG_CORR_Z_4_RANGEB (0)
#define VLXB_TP_UWR_LNG_CORR_Z_5_RANGEA (0)
#define VLXB_TP_UWR_LNG_CORR_Z_5_RANGEB (0)
#define VLXB_TP_DSS_TARGET_LITE_MCPS (2560)
#define VLXB_TP_DSS_TARGET_HISTO_MCPS (5120)
#define VLXB_TP_DSS_TARGET_HISTO_MZ_MCPS (5120)
#define VLXB_TP_DSS_TARGET_TIMED_MCPS (2560)
#define VLXB_TP_PHASECAL_TIMEOUT_LITE_US (1000)
#define VLXB_TP_PHASECAL_TIMEOUT_HIST_LONG_US (15000)
#define VLXB_TP_PHASECAL_TIMEOUT_HIST_MED_US (9000)
#define VLXB_TP_PHASECAL_TIMEOUT_HIST_SHORT_US (6000)
#define VLXB_TP_PHASECAL_TIMEOUT_MZ_LONG_US (15000)
#define VLXB_TP_PHASECAL_TIMEOUT_MZ_MED_US (9000)
#define VLXB_TP_PHASECAL_TIMEOUT_MZ_SHORT_US (6000)
#define VLXB_TP_PHASECAL_TIMEOUT_TIMED_US (1000)
#define VLXB_TP_MM_TIMEOUT_LITE_US (2000)
#define VLXB_TP_MM_TIMEOUT_HISTO_US (2000)
#define VLXB_TP_MM_TIMEOUT_MZ_US (2000)
#define VLXB_TP_MM_TIMEOUT_TIMED_US (2000)
#define VLXB_TP_RANGE_TIMEOUT_LITE_US (63000)
#define VLXB_TP_RANGE_TIMEOUT_HISTO_US (2500)
#define VLXB_TP_RANGE_TIMEOUT_MZ_US (2500)
#define VLXB_TP_RANGE_TIMEOUT_TIMED_US (13000)
#define VLXB_TP_MM_TIMEOUT_LPA_US (1)
#define VLXB_TP_RANGE_TIMEOUT_LPA_US (8000)
#define VLXB_TP_DSS_TARGET_VERY_SHORT_MCPS (10240)
#define VLXB_TP_PHASECAL_PATCH_POWER (0)
#define VLXB_TP_HIST_MERGE (1)
#define VLXB_TP_RESET_MERGE_THRESHOLD (15000)
#define VLXB_TP_HIST_MERGE_MAX_SIZE (6)

/* DEFAULTS: the tuning header's raw defines. */
#define VLXB_TUNINGPARM_CONSISTENCY_HIST_EVENT_SIGMA_DEFAULT (0)
#define VLXB_TUNINGPARM_CONSISTENCY_HIST_EVENT_SIGMA_MIN_SPAD_LIMIT_DEFAULT (2048)
#define VLXB_TUNINGPARM_CONSISTENCY_HIST_MIN_MAX_TOLERANCE_MM_DEFAULT (0)
#define VLXB_TUNINGPARM_CONSISTENCY_HIST_PHASE_TOLERANCE_DEFAULT (8)
#define VLXB_TUNINGPARM_CONSISTENCY_LITE_PHASE_TOLERANCE_DEFAULT (2)
#define VLXB_TUNINGPARM_DMAX_CFG_REFLECTANCE_ARRAY_0_DEFAULT (15)
#define VLXB_TUNINGPARM_DMAX_CFG_REFLECTANCE_ARRAY_1_DEFAULT (52)
#define VLXB_TUNINGPARM_DMAX_CFG_REFLECTANCE_ARRAY_2_DEFAULT (200)
#define VLXB_TUNINGPARM_DMAX_CFG_REFLECTANCE_ARRAY_3_DEFAULT (364)
#define VLXB_TUNINGPARM_DMAX_CFG_REFLECTANCE_ARRAY_4_DEFAULT (400)
#define VLXB_TUNINGPARM_DMAX_CFG_SIGNAL_THRESH_SIGMA_DEFAULT (32)
#define VLXB_TUNINGPARM_DYNXTALK_AVERAGED_XTALK_DELTA_DEFAULT (308)
#define VLXB_TUNINGPARM_DYNXTALK_CLIP_LIMIT_DEFAULT (10240)
#define VLXB_TUNINGPARM_DYNXTALK_MAX_SMUDGE_FACTOR_DEFAULT (2000)
#define VLXB_TUNINGPARM_DYNXTALK_NODETECT_AMB_THRESHOLD_KCPS_DEFAULT (57671680)
#define VLXB_TUNINGPARM_DYNXTALK_NODETECT_MIN_RANGE_MM_DEFAULT (900)
#define VLXB_TUNINGPARM_DYNXTALK_NODETECT_SAMPLE_LIMIT_DEFAULT (40)
#define VLXB_TUNINGPARM_DYNXTALK_NODETECT_XTALK_OFFSET_KCPS_DEFAULT (410)
#define VLXB_TUNINGPARM_DYNXTALK_NOISE_MARGIN_DEFAULT (100)
#define VLXB_TUNINGPARM_DYNXTALK_SAMPLE_LIMIT_DEFAULT (200)
#define VLXB_TUNINGPARM_DYNXTALK_SCALER_CALC_METHOD_DEFAULT (0)
#define VLXB_TUNINGPARM_DYNXTALK_SINGLE_XTALK_DELTA_DEFAULT (2048)
#define VLXB_TUNINGPARM_DYNXTALK_SMUDGE_COR_SINGLE_APPLY_DEFAULT (0)
#define VLXB_TUNINGPARM_DYNXTALK_SMUDGE_MARGIN_DEFAULT (0)
#define VLXB_TUNINGPARM_DYNXTALK_USER_SCALER_SET_DEFAULT (0)
#define VLXB_TUNINGPARM_DYNXTALK_XGRADIENT_SCALER_DEFAULT (256)
#define VLXB_TUNINGPARM_DYNXTALK_XTALK_AMB_THRESHOLD_DEFAULT (128)
#define VLXB_TUNINGPARM_DYNXTALK_XTALK_OFFSET_LIMIT_DEFAULT (0)
#define VLXB_TUNINGPARM_DYNXTALK_XTALK_OFFSET_LIMIT_HI_DEFAULT (0)
#define VLXB_TUNINGPARM_DYNXTALK_YGRADIENT_SCALER_DEFAULT (256)
#define VLXB_TUNINGPARM_HIST_ALGO_SELECT_DEFAULT (4)
#define VLXB_TUNINGPARM_HIST_AMB_EST_METHOD_DEFAULT (1)
#define VLXB_TUNINGPARM_HIST_AMB_EVENTS_SCALER_DEFAULT (4157)
#define VLXB_TUNINGPARM_HIST_AMB_THRESH_SIGMA_0_DEFAULT (80)
#define VLXB_TUNINGPARM_HIST_AMB_THRESH_SIGMA_1_DEFAULT (100)
#define VLXB_TUNINGPARM_HIST_FILTER_WOI_0_DEFAULT (1)
#define VLXB_TUNINGPARM_HIST_FILTER_WOI_1_DEFAULT (2)
#define VLXB_TUNINGPARM_HIST_GAIN_FACTOR_DEFAULT (1987)
#define VLXB_TUNINGPARM_HIST_MERGE_DEFAULT (1)
#define VLXB_TUNINGPARM_HIST_MERGE_MAX_SIZE_DEFAULT (6)
#define VLXB_TUNINGPARM_HIST_MIN_AMB_THRESH_EVENTS_DEFAULT (16)
#define VLXB_TUNINGPARM_HIST_NOISE_THRESHOLD_DEFAULT (50)
#define VLXB_TUNINGPARM_HIST_SIGMA_EST_REF_MM_DEFAULT (1)
#define VLXB_TUNINGPARM_HIST_SIGMA_THRESH_MM_DEFAULT (180)
#define VLXB_TUNINGPARM_HIST_SIGNAL_TOTAL_EVENTS_LIMIT_DEFAULT (100)
#define VLXB_TUNINGPARM_HIST_TARGET_ORDER_DEFAULT (1)
#define VLXB_TUNINGPARM_HIST_XTALK_MARGIN_KCPS_DEFAULT (0)
#define VLXB_TUNINGPARM_INITIAL_PHASE_REF_HISTO_LONG_RANGE_DEFAULT (6)
#define VLXB_TUNINGPARM_INITIAL_PHASE_REF_HISTO_MED_RANGE_DEFAULT (6)
#define VLXB_TUNINGPARM_INITIAL_PHASE_REF_HISTO_SHORT_RANGE_DEFAULT (6)
#define VLXB_TUNINGPARM_INITIAL_PHASE_REF_LITE_LONG_RANGE_DEFAULT (14)
#define VLXB_TUNINGPARM_INITIAL_PHASE_REF_LITE_MED_RANGE_DEFAULT (10)
#define VLXB_TUNINGPARM_INITIAL_PHASE_REF_LITE_SHORT_RANGE_DEFAULT (6)
#define VLXB_TUNINGPARM_INITIAL_PHASE_RTN_HISTO_LONG_RANGE_DEFAULT (9)
#define VLXB_TUNINGPARM_INITIAL_PHASE_RTN_HISTO_MED_RANGE_DEFAULT (5)
#define VLXB_TUNINGPARM_INITIAL_PHASE_RTN_HISTO_SHORT_RANGE_DEFAULT (3)
#define VLXB_TUNINGPARM_INITIAL_PHASE_RTN_LITE_LONG_RANGE_DEFAULT (14)
#define VLXB_TUNINGPARM_INITIAL_PHASE_RTN_LITE_MED_RANGE_DEFAULT (10)
#define VLXB_TUNINGPARM_INITIAL_PHASE_RTN_LITE_SHORT_RANGE_DEFAULT (6)
#define VLXB_TUNINGPARM_KEY_TABLE_VERSION_DEFAULT (14)
#define VLXB_TUNINGPARM_LITE_CAL_REPEAT_RATE_DEFAULT (0)
#define VLXB_TUNINGPARM_LITE_DSS_CONFIG_TARGET_TOTAL_RATE_MCPS_DEFAULT (2560)
#define VLXB_TUNINGPARM_LITE_FIRST_ORDER_SELECT_DEFAULT (0)
#define VLXB_TUNINGPARM_LITE_LONG_MIN_COUNT_RATE_RTN_MCPS_DEFAULT (128)
#define VLXB_TUNINGPARM_LITE_LONG_SIGMA_THRESH_MM_DEFAULT (60)
#define VLXB_TUNINGPARM_LITE_MED_MIN_COUNT_RATE_RTN_MCPS_DEFAULT (128)
#define VLXB_TUNINGPARM_LITE_MED_SIGMA_THRESH_MM_DEFAULT (60)
#define VLXB_TUNINGPARM_LITE_MIN_CLIP_MM_DEFAULT (0)
#define VLXB_TUNINGPARM_LITE_MM_CONFIG_TIMEOUT_US_DEFAULT (2000)
#define VLXB_TUNINGPARM_LITE_PHASECAL_CONFIG_TIMEOUT_US_DEFAULT (1000)
#define VLXB_TUNINGPARM_LITE_QUANTIFIER_DEFAULT (2)
#define VLXB_TUNINGPARM_LITE_RANGE_CONFIG_TIMEOUT_US_DEFAULT (63000)
#define VLXB_TUNINGPARM_LITE_RANGING_GAIN_FACTOR_DEFAULT (2011)
#define VLXB_TUNINGPARM_LITE_RIT_MULT_DEFAULT (64)
#define VLXB_TUNINGPARM_LITE_SEED_CONFIG_DEFAULT (2)
#define VLXB_TUNINGPARM_LITE_SHORT_MIN_COUNT_RATE_RTN_MCPS_DEFAULT (128)
#define VLXB_TUNINGPARM_LITE_SHORT_SIGMA_THRESH_MM_DEFAULT (60)
#define VLXB_TUNINGPARM_LITE_SIGMA_EST_AMB_WIDTH_NS_DEFAULT (16)
#define VLXB_TUNINGPARM_LITE_SIGMA_EST_PULSE_WIDTH_DEFAULT (8)
#define VLXB_TUNINGPARM_LITE_SIGMA_REF_MM_DEFAULT (1)
#define VLXB_TUNINGPARM_LITE_XTALK_MARGIN_KCPS_DEFAULT (0)
#define VLXB_TUNINGPARM_LLD_VERSION_DEFAULT (12180)
#define VLXB_TUNINGPARM_LOWPOWERAUTO_MM_CONFIG_TIMEOUT_US_DEFAULT (1)
#define VLXB_TUNINGPARM_LOWPOWERAUTO_RANGE_CONFIG_TIMEOUT_US_DEFAULT (8000)
#define VLXB_TUNINGPARM_LOWPOWERAUTO_VHV_LOOP_BOUND_DEFAULT (3)
#define VLXB_TUNINGPARM_MZ_DSS_CONFIG_TARGET_TOTAL_RATE_MCPS_DEFAULT (5120)
#define VLXB_TUNINGPARM_MZ_LONG_PHASECAL_CONFIG_TIMEOUT_US_DEFAULT (15000)
#define VLXB_TUNINGPARM_MZ_MED_PHASECAL_CONFIG_TIMEOUT_US_DEFAULT (9000)
#define VLXB_TUNINGPARM_MZ_MM_CONFIG_TIMEOUT_US_DEFAULT (2000)
#define VLXB_TUNINGPARM_MZ_RANGE_CONFIG_TIMEOUT_US_DEFAULT (2500)
#define VLXB_TUNINGPARM_MZ_SHORT_PHASECAL_CONFIG_TIMEOUT_US_DEFAULT (6000)
#define VLXB_TUNINGPARM_OFFSET_CAL_DSS_RATE_MCPS_DEFAULT (2560)
#define VLXB_TUNINGPARM_OFFSET_CAL_MM1_SAMPLES_DEFAULT (40)
#define VLXB_TUNINGPARM_OFFSET_CAL_MM2_SAMPLES_DEFAULT (9)
#define VLXB_TUNINGPARM_OFFSET_CAL_MM_TIMEOUT_US_DEFAULT (13000)
#define VLXB_TUNINGPARM_OFFSET_CAL_PHASECAL_TIMEOUT_US_DEFAULT (15000)
#define VLXB_TUNINGPARM_OFFSET_CAL_PRE_SAMPLES_DEFAULT (8)
#define VLXB_TUNINGPARM_OFFSET_CAL_RANGE_TIMEOUT_US_DEFAULT (13000)
#define VLXB_TUNINGPARM_PHASECAL_PATCH_POWER_DEFAULT (0)
#define VLXB_TUNINGPARM_PHASECAL_TARGET_DEFAULT (33)
#define VLXB_TUNINGPARM_RANGING_DSS_CONFIG_TARGET_TOTAL_RATE_MCPS_DEFAULT (5120)
#define VLXB_TUNINGPARM_RANGING_LONG_PHASECAL_CONFIG_TIMEOUT_US_DEFAULT (15000)
#define VLXB_TUNINGPARM_RANGING_MED_PHASECAL_CONFIG_TIMEOUT_US_DEFAULT (9000)
#define VLXB_TUNINGPARM_RANGING_MM_CONFIG_TIMEOUT_US_DEFAULT (2000)
#define VLXB_TUNINGPARM_RANGING_RANGE_CONFIG_TIMEOUT_US_DEFAULT (2500)
#define VLXB_TUNINGPARM_RANGING_SHORT_PHASECAL_CONFIG_TIMEOUT_US_DEFAULT (6000)
#define VLXB_TUNINGPARM_REFSPADCHAR_DEVICE_TEST_MODE_DEFAULT (8)
#define VLXB_TUNINGPARM_REFSPADCHAR_MAX_COUNTRATE_LIMIT_MCPS_DEFAULT (5120)
#define VLXB_TUNINGPARM_REFSPADCHAR_MIN_COUNTRATE_LIMIT_MCPS_DEFAULT (1280)
#define VLXB_TUNINGPARM_REFSPADCHAR_PHASECAL_TIMEOUT_US_DEFAULT (1000)
#define VLXB_TUNINGPARM_REFSPADCHAR_TARGET_COUNT_RATE_MCPS_DEFAULT (2560)
#define VLXB_TUNINGPARM_REFSPADCHAR_VCSEL_PERIOD_DEFAULT (11)
#define VLXB_TUNINGPARM_RESET_MERGE_THRESHOLD_DEFAULT (15000)
#define VLXB_TUNINGPARM_SPADMAP_RATE_LIMIT_MCPS_DEFAULT (12)
#define VLXB_TUNINGPARM_SPADMAP_VCSEL_PERIOD_DEFAULT (18)
#define VLXB_TUNINGPARM_SPADMAP_VCSEL_START_DEFAULT (15)
#define VLXB_TUNINGPARM_TIMED_DSS_CONFIG_TARGET_TOTAL_RATE_MCPS_DEFAULT (2560)
#define VLXB_TUNINGPARM_TIMED_MM_CONFIG_TIMEOUT_US_DEFAULT (2000)
#define VLXB_TUNINGPARM_TIMED_PHASECAL_CONFIG_TIMEOUT_US_DEFAULT (1000)
#define VLXB_TUNINGPARM_TIMED_RANGE_CONFIG_TIMEOUT_US_DEFAULT (13000)
#define VLXB_TUNINGPARM_TIMED_SEED_CONFIG_DEFAULT (1)
#define VLXB_TUNINGPARM_UWR_ENABLE_DEFAULT (1)
#define VLXB_TUNINGPARM_UWR_LONG_CORRECTION_ZONE_1_RANGEA_DEFAULT (3850)
#define VLXB_TUNINGPARM_UWR_LONG_CORRECTION_ZONE_1_RANGEB_DEFAULT (4600)
#define VLXB_TUNINGPARM_UWR_LONG_CORRECTION_ZONE_2_RANGEA_DEFAULT (3850)
#define VLXB_TUNINGPARM_UWR_LONG_CORRECTION_ZONE_2_RANGEB_DEFAULT (0)
#define VLXB_TUNINGPARM_UWR_LONG_CORRECTION_ZONE_3_RANGEA_DEFAULT (0)
#define VLXB_TUNINGPARM_UWR_LONG_CORRECTION_ZONE_3_RANGEB_DEFAULT (0)
#define VLXB_TUNINGPARM_UWR_LONG_CORRECTION_ZONE_4_RANGEA_DEFAULT (0)
#define VLXB_TUNINGPARM_UWR_LONG_CORRECTION_ZONE_4_RANGEB_DEFAULT (0)
#define VLXB_TUNINGPARM_UWR_LONG_CORRECTION_ZONE_5_RANGEA_DEFAULT (0)
#define VLXB_TUNINGPARM_UWR_LONG_CORRECTION_ZONE_5_RANGEB_DEFAULT (0)
#define VLXB_TUNINGPARM_UWR_LONG_ZONE_1_MAX_DEFAULT (1250)
#define VLXB_TUNINGPARM_UWR_LONG_ZONE_1_MIN_DEFAULT (250)
#define VLXB_TUNINGPARM_UWR_LONG_ZONE_2_MAX_DEFAULT (4500)
#define VLXB_TUNINGPARM_UWR_LONG_ZONE_2_MIN_DEFAULT (3250)
#define VLXB_TUNINGPARM_UWR_LONG_ZONE_3_MAX_DEFAULT (200)
#define VLXB_TUNINGPARM_UWR_LONG_ZONE_3_MIN_DEFAULT (-200)
#define VLXB_TUNINGPARM_UWR_LONG_ZONE_4_MAX_DEFAULT (0)
#define VLXB_TUNINGPARM_UWR_LONG_ZONE_4_MIN_DEFAULT (0)
#define VLXB_TUNINGPARM_UWR_LONG_ZONE_5_MAX_DEFAULT (0)
#define VLXB_TUNINGPARM_UWR_LONG_ZONE_5_MIN_DEFAULT (0)
#define VLXB_TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_1_RANGEA_DEFAULT (2300)
#define VLXB_TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_1_RANGEB_DEFAULT (0)
#define VLXB_TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_2_RANGEA_DEFAULT (2300)
#define VLXB_TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_2_RANGEB_DEFAULT (3050)
#define VLXB_TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_3_RANGEA_DEFAULT (4600)
#define VLXB_TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_3_RANGEB_DEFAULT (3050)
#define VLXB_TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_4_RANGEA_DEFAULT (4600)
#define VLXB_TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_4_RANGEB_DEFAULT (6200)
#define VLXB_TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_5_RANGEA_DEFAULT (0)
#define VLXB_TUNINGPARM_UWR_MEDIUM_CORRECTION_ZONE_5_RANGEB_DEFAULT (0)
#define VLXB_TUNINGPARM_UWR_MEDIUM_ZONE_1_MAX_DEFAULT (2750)
#define VLXB_TUNINGPARM_UWR_MEDIUM_ZONE_1_MIN_DEFAULT (2000)
#define VLXB_TUNINGPARM_UWR_MEDIUM_ZONE_2_MAX_DEFAULT (1000)
#define VLXB_TUNINGPARM_UWR_MEDIUM_ZONE_2_MIN_DEFAULT (250)
#define VLXB_TUNINGPARM_UWR_MEDIUM_ZONE_3_MAX_DEFAULT (1750)
#define VLXB_TUNINGPARM_UWR_MEDIUM_ZONE_3_MIN_DEFAULT (1250)
#define VLXB_TUNINGPARM_UWR_MEDIUM_ZONE_4_MAX_DEFAULT (1750)
#define VLXB_TUNINGPARM_UWR_MEDIUM_ZONE_4_MIN_DEFAULT (1250)
#define VLXB_TUNINGPARM_UWR_MEDIUM_ZONE_5_MAX_DEFAULT (200)
#define VLXB_TUNINGPARM_UWR_MEDIUM_ZONE_5_MIN_DEFAULT (-200)
#define VLXB_TUNINGPARM_VERSION_DEFAULT (30)
#define VLXB_TUNINGPARM_VERY_SHORT_DSS_RATE_MCPS_DEFAULT (10240)
#define VLXB_TUNINGPARM_VHV_LOOPBOUND_DEFAULT (129)
#define VLXB_TUNINGPARM_XTALK_DETECT_EVENT_SIGMA_DEFAULT (80)
#define VLXB_TUNINGPARM_XTALK_DETECT_MAX_SIGMA_MM_DEFAULT (140)
#define VLXB_TUNINGPARM_XTALK_DETECT_MAX_VALID_RANGE_MM_DEFAULT (50)
#define VLXB_TUNINGPARM_XTALK_DETECT_MAX_VALID_RATE_KCPS_DEFAULT (400)
#define VLXB_TUNINGPARM_XTALK_DETECT_MIN_MAX_TOLERANCE_DEFAULT (50)
#define VLXB_TUNINGPARM_XTALK_DETECT_MIN_VALID_RANGE_MM_DEFAULT (-50)
#define VLXB_TUNINGPARM_XTALK_EXTRACT_BIN_TIMEOUT_US_DEFAULT (10000)
#define VLXB_TUNINGPARM_XTALK_EXTRACT_DSS_RATE_MCPS_DEFAULT (5120)
#define VLXB_TUNINGPARM_XTALK_EXTRACT_DSS_TIMEOUT_US_DEFAULT (2000)
#define VLXB_TUNINGPARM_XTALK_EXTRACT_MAX_FILTER_THRESH_MM_DEFAULT (70)
#define VLXB_TUNINGPARM_XTALK_EXTRACT_MAX_VALID_RATE_KCPS_DEFAULT (640)
#define VLXB_TUNINGPARM_XTALK_EXTRACT_MIN_FILTER_THRESH_MM_DEFAULT (-70)
#define VLXB_TUNINGPARM_XTALK_EXTRACT_NUM_OF_SAMPLES_DEFAULT (7)
#define VLXB_TUNINGPARM_XTALK_EXTRACT_PHASECAL_TIMEOUT_US_DEFAULT (15000)
#define VLXB_TUNINGPARM_XTALK_EXTRACT_SIGMA_THRESHOLD_MM_DEFAULT (140)
#define VLXB_TUNINGPARM_ZONE_CAL_DSS_RATE_MCPS_DEFAULT (5120)
#define VLXB_TUNINGPARM_ZONE_CAL_DSS_TIMEOUT_US_DEFAULT (2000)
#define VLXB_TUNINGPARM_ZONE_CAL_PHASECAL_NUM_SAMPLES_DEFAULT (16)
#define VLXB_TUNINGPARM_ZONE_CAL_PHASECAL_TIMEOUT_US_DEFAULT (15000)
#define VLXB_TUNINGPARM_ZONE_CAL_RANGE_TIMEOUT_US_DEFAULT (1000)
#define VLXB_TUNINGPARM_ZONE_CAL_ZONE_NUM_SAMPLES_DEFAULT (8)

#endif /* DEPZ_VL53LX_BARE_TABLES_H */
