/* vl53lx_bare_tables.c — GENERATED by scripts/gen_vl53lx_bare_tables.py from
 * the Python SDK's vl53lx/uld/bare/regs.py; do not edit. */
#include "vl53lx_bare_tables.h"

#include <string.h>

const vlxb_block_geom vlxb_blocks[VLXB_BLK_COUNT] = {
    {0x0001, 11, 1}, /* static_nvm_managed */
    {0x000D, 23, 1}, /* customer_nvm_managed */
    {0x0024, 32, 1}, /* static_config */
    {0x0044, 22, 1}, /* general_config */
    {0x005A, 23, 1}, /* timing_config */
    {0x0071, 18, 1}, /* dynamic_config */
    {0x0083, 5, 1}, /* system_control */
    {0x0088, 44, 1}, /* system_results */
    {0x00B4, 33, 1}, /* core_results */
    {0x00D6, 56, 1}, /* debug_results */
    {0x010F, 49, 1}, /* nvm_copy_data */
    {0x0F20, 2, 1}, /* patch_debug */
    {0x0F24, 5, 1}, /* gph_general_config */
    {0x0F2F, 6, 1}, /* gph_static_config */
    {0x0F36, 16, 1}, /* gph_timing_config */
    {0x0F46, 2, 1}, /* fw_internal */
};

static int64_t get_be(const uint8_t *p, int width, uint64_t mask, int is_signed)
{
    uint64_t v = 0;
    int k, bits = width * 8;
    for (k = 0; k < width; k++) v = (v << 8) | p[k];
    v &= mask;
    if (is_signed && v >= ((uint64_t)1 << (bits - 1))) return (int64_t)v - ((int64_t)1 << bits);
    return (int64_t)v;
}

static void put_be(uint8_t *p, int width, uint64_t mask, int64_t value)
{
    uint64_t v = (uint64_t)value & mask;
    int k;
    if (width < 8) v &= ((uint64_t)1 << (width * 8)) - 1;
    for (k = width - 1; k >= 0; k--) {
        p[k] = (uint8_t)v;
        v >>= 8;
    }
}

void vlxb_decode(vlxb_image *img, vlxb_block_id id, const uint8_t *raw)
{
    switch (id) {
    case VLXB_BLK_STATIC_NVM_MANAGED: {
        vlxb_static_nvm_managed *s = &img->static_nvm_managed;
        memcpy(s->raw, raw, 11);
        s->i2c_slave__device_address = get_be(raw + 0, 1, 0x7Fu, 0);
        s->ana_config__vhv_ref_sel_vddpix = get_be(raw + 1, 1, 0xFu, 0);
        s->ana_config__vhv_ref_sel_vquench = get_be(raw + 2, 1, 0x7Fu, 0);
        s->ana_config__reg_avdd1v2_sel = get_be(raw + 3, 1, 0x3u, 0);
        s->ana_config__fast_osc__trim = get_be(raw + 4, 1, 0x7Fu, 0);
        s->osc_measured__fast_osc__frequency = get_be(raw + 5, 2, 0xFFFFu, 0);
        s->vhv_config__timeout_macrop_loop_bound = get_be(raw + 7, 1, 0xFFu, 0);
        s->vhv_config__count_thresh = get_be(raw + 8, 1, 0xFFu, 0);
        s->vhv_config__offset = get_be(raw + 9, 1, 0x3Fu, 0);
        s->vhv_config__init = get_be(raw + 10, 1, 0xFFu, 0);
        break;
    }
    case VLXB_BLK_CUSTOMER_NVM_MANAGED: {
        vlxb_customer_nvm_managed *s = &img->customer_nvm_managed;
        memcpy(s->raw, raw, 23);
        s->global_config__spad_enables_ref_0 = get_be(raw + 0, 1, 0xFFu, 0);
        s->global_config__spad_enables_ref_1 = get_be(raw + 1, 1, 0xFFu, 0);
        s->global_config__spad_enables_ref_2 = get_be(raw + 2, 1, 0xFFu, 0);
        s->global_config__spad_enables_ref_3 = get_be(raw + 3, 1, 0xFFu, 0);
        s->global_config__spad_enables_ref_4 = get_be(raw + 4, 1, 0xFFu, 0);
        s->global_config__spad_enables_ref_5 = get_be(raw + 5, 1, 0xFu, 0);
        s->global_config__ref_en_start_select = get_be(raw + 6, 1, 0xFFu, 0);
        s->ref_spad_man__num_requested_ref_spads = get_be(raw + 7, 1, 0x3Fu, 0);
        s->ref_spad_man__ref_location = get_be(raw + 8, 1, 0x3u, 0);
        s->algo__crosstalk_compensation_plane_offset_kcps = get_be(raw + 9, 2, 0xFFFFu, 0);
        s->algo__crosstalk_compensation_x_plane_gradient_kcps = get_be(raw + 11, 2, 0xFFFFu, 1);
        s->algo__crosstalk_compensation_y_plane_gradient_kcps = get_be(raw + 13, 2, 0xFFFFu, 1);
        s->ref_spad_char__total_rate_target_mcps = get_be(raw + 15, 2, 0xFFFFu, 0);
        s->algo__part_to_part_range_offset_mm = get_be(raw + 17, 2, 0x1FFFu, 1);
        s->mm_config__inner_offset_mm = get_be(raw + 19, 2, 0xFFFFu, 1);
        s->mm_config__outer_offset_mm = get_be(raw + 21, 2, 0xFFFFu, 1);
        break;
    }
    case VLXB_BLK_STATIC_CONFIG: {
        vlxb_static_config *s = &img->static_config;
        memcpy(s->raw, raw, 32);
        s->dss_config__target_total_rate_mcps = get_be(raw + 0, 2, 0xFFFFu, 0);
        s->debug__ctrl = get_be(raw + 2, 1, 0x1u, 0);
        s->test_mode__ctrl = get_be(raw + 3, 1, 0xFu, 0);
        s->clk_gating__ctrl = get_be(raw + 4, 1, 0xFu, 0);
        s->nvm_bist__ctrl = get_be(raw + 5, 1, 0x1Fu, 0);
        s->nvm_bist__num_nvm_words = get_be(raw + 6, 1, 0x7Fu, 0);
        s->nvm_bist__start_address = get_be(raw + 7, 1, 0x7Fu, 0);
        s->host_if__status = get_be(raw + 8, 1, 0x1u, 0);
        s->pad_i2c_hv__config = get_be(raw + 9, 1, 0xFFu, 0);
        s->pad_i2c_hv__extsup_config = get_be(raw + 10, 1, 0x1u, 0);
        s->gpio_hv_pad__ctrl = get_be(raw + 11, 1, 0x3u, 0);
        s->gpio_hv_mux__ctrl = get_be(raw + 12, 1, 0x1Fu, 0);
        s->gpio__tio_hv_status = get_be(raw + 13, 1, 0x3u, 0);
        s->gpio__fio_hv_status = get_be(raw + 14, 1, 0x3u, 0);
        s->ana_config__spad_sel_pswidth = get_be(raw + 15, 1, 0x7u, 0);
        s->ana_config__vcsel_pulse_width_offset = get_be(raw + 16, 1, 0x1Fu, 0);
        s->ana_config__fast_osc__config_ctrl = get_be(raw + 17, 1, 0x1u, 0);
        s->sigma_estimator__effective_pulse_width_ns = get_be(raw + 18, 1, 0xFFu, 0);
        s->sigma_estimator__effective_ambient_width_ns = get_be(raw + 19, 1, 0xFFu, 0);
        s->sigma_estimator__sigma_ref_mm = get_be(raw + 20, 1, 0xFFu, 0);
        s->algo__crosstalk_compensation_valid_height_mm = get_be(raw + 21, 1, 0xFFu, 0);
        s->spare_host_config__static_config_spare_0 = get_be(raw + 22, 1, 0xFFu, 0);
        s->spare_host_config__static_config_spare_1 = get_be(raw + 23, 1, 0xFFu, 0);
        s->algo__range_ignore_threshold_mcps = get_be(raw + 24, 2, 0xFFFFu, 0);
        s->algo__range_ignore_valid_height_mm = get_be(raw + 26, 1, 0xFFu, 0);
        s->algo__range_min_clip = get_be(raw + 27, 1, 0xFFu, 0);
        s->algo__consistency_check__tolerance = get_be(raw + 28, 1, 0xFu, 0);
        s->spare_host_config__static_config_spare_2 = get_be(raw + 29, 1, 0xFFu, 0);
        s->sd_config__reset_stages_msb = get_be(raw + 30, 1, 0xFu, 0);
        s->sd_config__reset_stages_lsb = get_be(raw + 31, 1, 0xFFu, 0);
        break;
    }
    case VLXB_BLK_GENERAL_CONFIG: {
        vlxb_general_config *s = &img->general_config;
        memcpy(s->raw, raw, 22);
        s->gph_config__stream_count_update_value = get_be(raw + 0, 1, 0xFFu, 0);
        s->global_config__stream_divider = get_be(raw + 1, 1, 0xFFu, 0);
        s->system__interrupt_config_gpio = get_be(raw + 2, 1, 0xFFu, 0);
        s->cal_config__vcsel_start = get_be(raw + 3, 1, 0x7Fu, 0);
        s->cal_config__repeat_rate = get_be(raw + 4, 2, 0xFFFu, 0);
        s->global_config__vcsel_width = get_be(raw + 6, 1, 0x7Fu, 0);
        s->phasecal_config__timeout_macrop = get_be(raw + 7, 1, 0xFFu, 0);
        s->phasecal_config__target = get_be(raw + 8, 1, 0xFFu, 0);
        s->phasecal_config__override = get_be(raw + 9, 1, 0x1u, 0);
        s->dss_config__roi_mode_control = get_be(raw + 11, 1, 0x7u, 0);
        s->system__thresh_rate_high = get_be(raw + 12, 2, 0xFFFFu, 0);
        s->system__thresh_rate_low = get_be(raw + 14, 2, 0xFFFFu, 0);
        s->dss_config__manual_effective_spads_select = get_be(raw + 16, 2, 0xFFFFu, 0);
        s->dss_config__manual_block_select = get_be(raw + 18, 1, 0xFFu, 0);
        s->dss_config__aperture_attenuation = get_be(raw + 19, 1, 0xFFu, 0);
        s->dss_config__max_spads_limit = get_be(raw + 20, 1, 0xFFu, 0);
        s->dss_config__min_spads_limit = get_be(raw + 21, 1, 0xFFu, 0);
        break;
    }
    case VLXB_BLK_TIMING_CONFIG: {
        vlxb_timing_config *s = &img->timing_config;
        memcpy(s->raw, raw, 23);
        s->mm_config__timeout_macrop_a_hi = get_be(raw + 0, 1, 0xFu, 0);
        s->mm_config__timeout_macrop_a_lo = get_be(raw + 1, 1, 0xFFu, 0);
        s->mm_config__timeout_macrop_b_hi = get_be(raw + 2, 1, 0xFu, 0);
        s->mm_config__timeout_macrop_b_lo = get_be(raw + 3, 1, 0xFFu, 0);
        s->range_config__timeout_macrop_a_hi = get_be(raw + 4, 1, 0xFu, 0);
        s->range_config__timeout_macrop_a_lo = get_be(raw + 5, 1, 0xFFu, 0);
        s->range_config__vcsel_period_a = get_be(raw + 6, 1, 0x3Fu, 0);
        s->range_config__timeout_macrop_b_hi = get_be(raw + 7, 1, 0xFu, 0);
        s->range_config__timeout_macrop_b_lo = get_be(raw + 8, 1, 0xFFu, 0);
        s->range_config__vcsel_period_b = get_be(raw + 9, 1, 0x3Fu, 0);
        s->range_config__sigma_thresh = get_be(raw + 10, 2, 0xFFFFu, 0);
        s->range_config__min_count_rate_rtn_limit_mcps = get_be(raw + 12, 2, 0xFFFFu, 0);
        s->range_config__valid_phase_low = get_be(raw + 14, 1, 0xFFu, 0);
        s->range_config__valid_phase_high = get_be(raw + 15, 1, 0xFFu, 0);
        s->system__intermeasurement_period = get_be(raw + 18, 4, 0xFFFFFFFFu, 0);
        s->system__fractional_enable = get_be(raw + 22, 1, 0x1u, 0);
        break;
    }
    case VLXB_BLK_DYNAMIC_CONFIG: {
        vlxb_dynamic_config *s = &img->dynamic_config;
        memcpy(s->raw, raw, 18);
        s->system__grouped_parameter_hold_0 = get_be(raw + 0, 1, 0x3u, 0);
        s->system__thresh_high = get_be(raw + 1, 2, 0xFFFFu, 0);
        s->system__thresh_low = get_be(raw + 3, 2, 0xFFFFu, 0);
        s->system__enable_xtalk_per_quadrant = get_be(raw + 5, 1, 0x1u, 0);
        s->system__seed_config = get_be(raw + 6, 1, 0x7u, 0);
        s->sd_config__woi_sd0 = get_be(raw + 7, 1, 0xFFu, 0);
        s->sd_config__woi_sd1 = get_be(raw + 8, 1, 0xFFu, 0);
        s->sd_config__initial_phase_sd0 = get_be(raw + 9, 1, 0x7Fu, 0);
        s->sd_config__initial_phase_sd1 = get_be(raw + 10, 1, 0x7Fu, 0);
        s->system__grouped_parameter_hold_1 = get_be(raw + 11, 1, 0x3u, 0);
        s->sd_config__first_order_select = get_be(raw + 12, 1, 0x3u, 0);
        s->sd_config__quantifier = get_be(raw + 13, 1, 0xFu, 0);
        s->roi_config__user_roi_centre_spad = get_be(raw + 14, 1, 0xFFu, 0);
        s->roi_config__user_roi_requested_global_xy_size = get_be(raw + 15, 1, 0xFFu, 0);
        s->system__sequence_config = get_be(raw + 16, 1, 0xFFu, 0);
        s->system__grouped_parameter_hold = get_be(raw + 17, 1, 0x3u, 0);
        break;
    }
    case VLXB_BLK_SYSTEM_CONTROL: {
        vlxb_system_control *s = &img->system_control;
        memcpy(s->raw, raw, 5);
        s->power_management__go1_power_force = get_be(raw + 0, 1, 0x1u, 0);
        s->system__stream_count_ctrl = get_be(raw + 1, 1, 0x1u, 0);
        s->firmware__enable = get_be(raw + 2, 1, 0x1u, 0);
        s->system__interrupt_clear = get_be(raw + 3, 1, 0x3u, 0);
        s->system__mode_start = get_be(raw + 4, 1, 0xFFu, 0);
        break;
    }
    case VLXB_BLK_SYSTEM_RESULTS: {
        vlxb_system_results *s = &img->system_results;
        memcpy(s->raw, raw, 44);
        s->result__interrupt_status = get_be(raw + 0, 1, 0x3Fu, 0);
        s->result__range_status = get_be(raw + 1, 1, 0xFFu, 0);
        s->result__report_status = get_be(raw + 2, 1, 0xFu, 0);
        s->result__stream_count = get_be(raw + 3, 1, 0xFFu, 0);
        s->result__dss_actual_effective_spads_sd0 = get_be(raw + 4, 2, 0xFFFFu, 0);
        s->result__peak_signal_count_rate_mcps_sd0 = get_be(raw + 6, 2, 0xFFFFu, 0);
        s->result__ambient_count_rate_mcps_sd0 = get_be(raw + 8, 2, 0xFFFFu, 0);
        s->result__sigma_sd0 = get_be(raw + 10, 2, 0xFFFFu, 0);
        s->result__phase_sd0 = get_be(raw + 12, 2, 0xFFFFu, 0);
        s->result__final_crosstalk_corrected_range_mm_sd0 = get_be(raw + 14, 2, 0xFFFFu, 0);
        s->result__peak_signal_count_rate_crosstalk_corrected_mcps_sd0 = get_be(raw + 16, 2, 0xFFFFu, 0);
        s->result__mm_inner_actual_effective_spads_sd0 = get_be(raw + 18, 2, 0xFFFFu, 0);
        s->result__mm_outer_actual_effective_spads_sd0 = get_be(raw + 20, 2, 0xFFFFu, 0);
        s->result__avg_signal_count_rate_mcps_sd0 = get_be(raw + 22, 2, 0xFFFFu, 0);
        s->result__dss_actual_effective_spads_sd1 = get_be(raw + 24, 2, 0xFFFFu, 0);
        s->result__peak_signal_count_rate_mcps_sd1 = get_be(raw + 26, 2, 0xFFFFu, 0);
        s->result__ambient_count_rate_mcps_sd1 = get_be(raw + 28, 2, 0xFFFFu, 0);
        s->result__sigma_sd1 = get_be(raw + 30, 2, 0xFFFFu, 0);
        s->result__phase_sd1 = get_be(raw + 32, 2, 0xFFFFu, 0);
        s->result__final_crosstalk_corrected_range_mm_sd1 = get_be(raw + 34, 2, 0xFFFFu, 0);
        s->result__spare_0_sd1 = get_be(raw + 36, 2, 0xFFFFu, 0);
        s->result__spare_1_sd1 = get_be(raw + 38, 2, 0xFFFFu, 0);
        s->result__spare_2_sd1 = get_be(raw + 40, 2, 0xFFFFu, 0);
        s->result__spare_3_sd1 = get_be(raw + 42, 1, 0xFFu, 0);
        s->result__thresh_info = get_be(raw + 43, 1, 0xFFu, 0);
        break;
    }
    case VLXB_BLK_CORE_RESULTS: {
        vlxb_core_results *s = &img->core_results;
        memcpy(s->raw, raw, 33);
        s->result_core__ambient_window_events_sd0 = get_be(raw + 0, 4, 0xFFFFFFFFu, 0);
        s->result_core__ranging_total_events_sd0 = get_be(raw + 4, 4, 0xFFFFFFFFu, 0);
        s->result_core__signal_total_events_sd0 = get_be(raw + 8, 4, 0xFFFFFFFFu, 1);
        s->result_core__total_periods_elapsed_sd0 = get_be(raw + 12, 4, 0xFFFFFFFFu, 0);
        s->result_core__ambient_window_events_sd1 = get_be(raw + 16, 4, 0xFFFFFFFFu, 0);
        s->result_core__ranging_total_events_sd1 = get_be(raw + 20, 4, 0xFFFFFFFFu, 0);
        s->result_core__signal_total_events_sd1 = get_be(raw + 24, 4, 0xFFFFFFFFu, 1);
        s->result_core__total_periods_elapsed_sd1 = get_be(raw + 28, 4, 0xFFFFFFFFu, 0);
        s->result_core__spare_0 = get_be(raw + 32, 1, 0xFFu, 0);
        break;
    }
    case VLXB_BLK_DEBUG_RESULTS: {
        vlxb_debug_results *s = &img->debug_results;
        memcpy(s->raw, raw, 56);
        s->phasecal_result__reference_phase = get_be(raw + 0, 2, 0xFFFFu, 0);
        s->phasecal_result__vcsel_start = get_be(raw + 2, 1, 0x7Fu, 0);
        s->ref_spad_char_result__num_actual_ref_spads = get_be(raw + 3, 1, 0x3Fu, 0);
        s->ref_spad_char_result__ref_location = get_be(raw + 4, 1, 0x3u, 0);
        s->vhv_result__coldboot_status = get_be(raw + 5, 1, 0x1u, 0);
        s->vhv_result__search_result = get_be(raw + 6, 1, 0x3Fu, 0);
        s->vhv_result__latest_setting = get_be(raw + 7, 1, 0x3Fu, 0);
        s->result__osc_calibrate_val = get_be(raw + 8, 2, 0x3FFu, 0);
        s->ana_config__powerdown_go1 = get_be(raw + 10, 1, 0x3u, 0);
        s->ana_config__ref_bg_ctrl = get_be(raw + 11, 1, 0x3u, 0);
        s->ana_config__regdvdd1v2_ctrl = get_be(raw + 12, 1, 0xFu, 0);
        s->ana_config__osc_slow_ctrl = get_be(raw + 13, 1, 0x7u, 0);
        s->test_mode__status = get_be(raw + 14, 1, 0x1u, 0);
        s->firmware__system_status = get_be(raw + 15, 1, 0x3u, 0);
        s->firmware__mode_status = get_be(raw + 16, 1, 0xFFu, 0);
        s->firmware__secondary_mode_status = get_be(raw + 17, 1, 0xFFu, 0);
        s->firmware__cal_repeat_rate_counter = get_be(raw + 18, 2, 0xFFFu, 0);
        s->gph__system__thresh_high = get_be(raw + 22, 2, 0xFFFFu, 0);
        s->gph__system__thresh_low = get_be(raw + 24, 2, 0xFFFFu, 0);
        s->gph__system__enable_xtalk_per_quadrant = get_be(raw + 26, 1, 0x1u, 0);
        s->gph__spare_0 = get_be(raw + 27, 1, 0x7u, 0);
        s->gph__sd_config__woi_sd0 = get_be(raw + 28, 1, 0xFFu, 0);
        s->gph__sd_config__woi_sd1 = get_be(raw + 29, 1, 0xFFu, 0);
        s->gph__sd_config__initial_phase_sd0 = get_be(raw + 30, 1, 0x7Fu, 0);
        s->gph__sd_config__initial_phase_sd1 = get_be(raw + 31, 1, 0x7Fu, 0);
        s->gph__sd_config__first_order_select = get_be(raw + 32, 1, 0x3u, 0);
        s->gph__sd_config__quantifier = get_be(raw + 33, 1, 0xFu, 0);
        s->gph__roi_config__user_roi_centre_spad = get_be(raw + 34, 1, 0xFFu, 0);
        s->gph__roi_config__user_roi_requested_global_xy_size = get_be(raw + 35, 1, 0xFFu, 0);
        s->gph__system__sequence_config = get_be(raw + 36, 1, 0xFFu, 0);
        s->gph__gph_id = get_be(raw + 37, 1, 0x1u, 0);
        s->system__interrupt_set = get_be(raw + 38, 1, 0x3u, 0);
        s->interrupt_manager__enables = get_be(raw + 39, 1, 0x1Fu, 0);
        s->interrupt_manager__clear = get_be(raw + 40, 1, 0x1Fu, 0);
        s->interrupt_manager__status = get_be(raw + 41, 1, 0x1Fu, 0);
        s->mcu_to_host_bank__wr_access_en = get_be(raw + 42, 1, 0x1u, 0);
        s->power_management__go1_reset_status = get_be(raw + 43, 1, 0x1u, 0);
        s->pad_startup_mode__value_ro = get_be(raw + 44, 1, 0x3u, 0);
        s->pad_startup_mode__value_ctrl = get_be(raw + 45, 1, 0x3Fu, 0);
        s->pll_period_us = get_be(raw + 46, 4, 0x3FFFFu, 0);
        s->interrupt_scheduler__data_out = get_be(raw + 50, 4, 0xFFFFFFFFu, 0);
        s->nvm_bist__complete = get_be(raw + 54, 1, 0x1u, 0);
        s->nvm_bist__status = get_be(raw + 55, 1, 0x1u, 0);
        break;
    }
    case VLXB_BLK_NVM_COPY_DATA: {
        vlxb_nvm_copy_data *s = &img->nvm_copy_data;
        memcpy(s->raw, raw, 49);
        s->identification__model_id = get_be(raw + 0, 1, 0xFFu, 0);
        s->identification__module_type = get_be(raw + 1, 1, 0xFFu, 0);
        s->identification__revision_id = get_be(raw + 2, 1, 0xFFu, 0);
        s->identification__module_id = get_be(raw + 3, 2, 0xFFFFu, 0);
        s->ana_config__fast_osc__trim_max = get_be(raw + 5, 1, 0x7Fu, 0);
        s->ana_config__fast_osc__freq_set = get_be(raw + 6, 1, 0x7u, 0);
        s->ana_config__vcsel_trim = get_be(raw + 7, 1, 0x7u, 0);
        s->ana_config__vcsel_selion = get_be(raw + 8, 1, 0x3Fu, 0);
        s->ana_config__vcsel_selion_max = get_be(raw + 9, 1, 0x3Fu, 0);
        s->protected_laser_safety__lock_bit = get_be(raw + 10, 1, 0x1u, 0);
        s->laser_safety__key = get_be(raw + 11, 1, 0x7Fu, 0);
        s->laser_safety__key_ro = get_be(raw + 12, 1, 0x1u, 0);
        s->laser_safety__clip = get_be(raw + 13, 1, 0x3Fu, 0);
        s->laser_safety__mult = get_be(raw + 14, 1, 0x3Fu, 0);
        s->global_config__spad_enables_rtn_0 = get_be(raw + 15, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_1 = get_be(raw + 16, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_2 = get_be(raw + 17, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_3 = get_be(raw + 18, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_4 = get_be(raw + 19, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_5 = get_be(raw + 20, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_6 = get_be(raw + 21, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_7 = get_be(raw + 22, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_8 = get_be(raw + 23, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_9 = get_be(raw + 24, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_10 = get_be(raw + 25, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_11 = get_be(raw + 26, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_12 = get_be(raw + 27, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_13 = get_be(raw + 28, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_14 = get_be(raw + 29, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_15 = get_be(raw + 30, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_16 = get_be(raw + 31, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_17 = get_be(raw + 32, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_18 = get_be(raw + 33, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_19 = get_be(raw + 34, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_20 = get_be(raw + 35, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_21 = get_be(raw + 36, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_22 = get_be(raw + 37, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_23 = get_be(raw + 38, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_24 = get_be(raw + 39, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_25 = get_be(raw + 40, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_26 = get_be(raw + 41, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_27 = get_be(raw + 42, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_28 = get_be(raw + 43, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_29 = get_be(raw + 44, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_30 = get_be(raw + 45, 1, 0xFFu, 0);
        s->global_config__spad_enables_rtn_31 = get_be(raw + 46, 1, 0xFFu, 0);
        s->roi_config__mode_roi_centre_spad = get_be(raw + 47, 1, 0xFFu, 0);
        s->roi_config__mode_roi_xy_size = get_be(raw + 48, 1, 0xFFu, 0);
        break;
    }
    case VLXB_BLK_PATCH_DEBUG: {
        vlxb_patch_debug *s = &img->patch_debug;
        memcpy(s->raw, raw, 2);
        s->result__debug_status = get_be(raw + 0, 1, 0xFFu, 0);
        s->result__debug_stage = get_be(raw + 1, 1, 0xFFu, 0);
        break;
    }
    case VLXB_BLK_GPH_GENERAL_CONFIG: {
        vlxb_gph_general_config *s = &img->gph_general_config;
        memcpy(s->raw, raw, 5);
        s->gph__system__thresh_rate_high = get_be(raw + 0, 2, 0xFFFFu, 0);
        s->gph__system__thresh_rate_low = get_be(raw + 2, 2, 0xFFFFu, 0);
        s->gph__system__interrupt_config_gpio = get_be(raw + 4, 1, 0xFFu, 0);
        break;
    }
    case VLXB_BLK_GPH_STATIC_CONFIG: {
        vlxb_gph_static_config *s = &img->gph_static_config;
        memcpy(s->raw, raw, 6);
        s->gph__dss_config__roi_mode_control = get_be(raw + 0, 1, 0x7u, 0);
        s->gph__dss_config__manual_effective_spads_select = get_be(raw + 1, 2, 0xFFFFu, 0);
        s->gph__dss_config__manual_block_select = get_be(raw + 3, 1, 0xFFu, 0);
        s->gph__dss_config__max_spads_limit = get_be(raw + 4, 1, 0xFFu, 0);
        s->gph__dss_config__min_spads_limit = get_be(raw + 5, 1, 0xFFu, 0);
        break;
    }
    case VLXB_BLK_GPH_TIMING_CONFIG: {
        vlxb_gph_timing_config *s = &img->gph_timing_config;
        memcpy(s->raw, raw, 16);
        s->gph__mm_config__timeout_macrop_a_hi = get_be(raw + 0, 1, 0xFu, 0);
        s->gph__mm_config__timeout_macrop_a_lo = get_be(raw + 1, 1, 0xFFu, 0);
        s->gph__mm_config__timeout_macrop_b_hi = get_be(raw + 2, 1, 0xFu, 0);
        s->gph__mm_config__timeout_macrop_b_lo = get_be(raw + 3, 1, 0xFFu, 0);
        s->gph__range_config__timeout_macrop_a_hi = get_be(raw + 4, 1, 0xFu, 0);
        s->gph__range_config__timeout_macrop_a_lo = get_be(raw + 5, 1, 0xFFu, 0);
        s->gph__range_config__vcsel_period_a = get_be(raw + 6, 1, 0x3Fu, 0);
        s->gph__range_config__vcsel_period_b = get_be(raw + 7, 1, 0x3Fu, 0);
        s->gph__range_config__timeout_macrop_b_hi = get_be(raw + 8, 1, 0xFu, 0);
        s->gph__range_config__timeout_macrop_b_lo = get_be(raw + 9, 1, 0xFFu, 0);
        s->gph__range_config__sigma_thresh = get_be(raw + 10, 2, 0xFFFFu, 0);
        s->gph__range_config__min_count_rate_rtn_limit_mcps = get_be(raw + 12, 2, 0xFFFFu, 0);
        s->gph__range_config__valid_phase_low = get_be(raw + 14, 1, 0xFFu, 0);
        s->gph__range_config__valid_phase_high = get_be(raw + 15, 1, 0xFFu, 0);
        break;
    }
    case VLXB_BLK_FW_INTERNAL: {
        vlxb_fw_internal *s = &img->fw_internal;
        memcpy(s->raw, raw, 2);
        s->firmware__internal_stream_count_div = get_be(raw + 0, 1, 0xFFu, 0);
        s->firmware__internal_stream_counter_val = get_be(raw + 1, 1, 0xFFu, 0);
        break;
    }
    default:
        break;
    }
}

void vlxb_encode(const vlxb_image *img, vlxb_block_id id, uint8_t *out)
{
    switch (id) {
    case VLXB_BLK_STATIC_NVM_MANAGED: {
        const vlxb_static_nvm_managed *s = &img->static_nvm_managed;
        memcpy(out, s->raw, 11);
        put_be(out + 0, 1, 0x7Fu, s->i2c_slave__device_address);
        put_be(out + 1, 1, 0xFu, s->ana_config__vhv_ref_sel_vddpix);
        put_be(out + 2, 1, 0x7Fu, s->ana_config__vhv_ref_sel_vquench);
        put_be(out + 3, 1, 0x3u, s->ana_config__reg_avdd1v2_sel);
        put_be(out + 4, 1, 0x7Fu, s->ana_config__fast_osc__trim);
        put_be(out + 5, 2, 0xFFFFu, s->osc_measured__fast_osc__frequency);
        put_be(out + 7, 1, 0xFFu, s->vhv_config__timeout_macrop_loop_bound);
        put_be(out + 8, 1, 0xFFu, s->vhv_config__count_thresh);
        put_be(out + 9, 1, 0x3Fu, s->vhv_config__offset);
        put_be(out + 10, 1, 0xFFu, s->vhv_config__init);
        break;
    }
    case VLXB_BLK_CUSTOMER_NVM_MANAGED: {
        const vlxb_customer_nvm_managed *s = &img->customer_nvm_managed;
        memcpy(out, s->raw, 23);
        put_be(out + 0, 1, 0xFFu, s->global_config__spad_enables_ref_0);
        put_be(out + 1, 1, 0xFFu, s->global_config__spad_enables_ref_1);
        put_be(out + 2, 1, 0xFFu, s->global_config__spad_enables_ref_2);
        put_be(out + 3, 1, 0xFFu, s->global_config__spad_enables_ref_3);
        put_be(out + 4, 1, 0xFFu, s->global_config__spad_enables_ref_4);
        put_be(out + 5, 1, 0xFu, s->global_config__spad_enables_ref_5);
        put_be(out + 6, 1, 0xFFu, s->global_config__ref_en_start_select);
        put_be(out + 7, 1, 0x3Fu, s->ref_spad_man__num_requested_ref_spads);
        put_be(out + 8, 1, 0x3u, s->ref_spad_man__ref_location);
        put_be(out + 9, 2, 0xFFFFu, s->algo__crosstalk_compensation_plane_offset_kcps);
        put_be(out + 11, 2, 0xFFFFu, s->algo__crosstalk_compensation_x_plane_gradient_kcps);
        put_be(out + 13, 2, 0xFFFFu, s->algo__crosstalk_compensation_y_plane_gradient_kcps);
        put_be(out + 15, 2, 0xFFFFu, s->ref_spad_char__total_rate_target_mcps);
        put_be(out + 17, 2, 0x1FFFu, s->algo__part_to_part_range_offset_mm);
        put_be(out + 19, 2, 0xFFFFu, s->mm_config__inner_offset_mm);
        put_be(out + 21, 2, 0xFFFFu, s->mm_config__outer_offset_mm);
        break;
    }
    case VLXB_BLK_STATIC_CONFIG: {
        const vlxb_static_config *s = &img->static_config;
        memcpy(out, s->raw, 32);
        put_be(out + 0, 2, 0xFFFFu, s->dss_config__target_total_rate_mcps);
        put_be(out + 2, 1, 0x1u, s->debug__ctrl);
        put_be(out + 3, 1, 0xFu, s->test_mode__ctrl);
        put_be(out + 4, 1, 0xFu, s->clk_gating__ctrl);
        put_be(out + 5, 1, 0x1Fu, s->nvm_bist__ctrl);
        put_be(out + 6, 1, 0x7Fu, s->nvm_bist__num_nvm_words);
        put_be(out + 7, 1, 0x7Fu, s->nvm_bist__start_address);
        put_be(out + 8, 1, 0x1u, s->host_if__status);
        put_be(out + 9, 1, 0xFFu, s->pad_i2c_hv__config);
        put_be(out + 10, 1, 0x1u, s->pad_i2c_hv__extsup_config);
        put_be(out + 11, 1, 0x3u, s->gpio_hv_pad__ctrl);
        put_be(out + 12, 1, 0x1Fu, s->gpio_hv_mux__ctrl);
        put_be(out + 13, 1, 0x3u, s->gpio__tio_hv_status);
        put_be(out + 14, 1, 0x3u, s->gpio__fio_hv_status);
        put_be(out + 15, 1, 0x7u, s->ana_config__spad_sel_pswidth);
        put_be(out + 16, 1, 0x1Fu, s->ana_config__vcsel_pulse_width_offset);
        put_be(out + 17, 1, 0x1u, s->ana_config__fast_osc__config_ctrl);
        put_be(out + 18, 1, 0xFFu, s->sigma_estimator__effective_pulse_width_ns);
        put_be(out + 19, 1, 0xFFu, s->sigma_estimator__effective_ambient_width_ns);
        put_be(out + 20, 1, 0xFFu, s->sigma_estimator__sigma_ref_mm);
        put_be(out + 21, 1, 0xFFu, s->algo__crosstalk_compensation_valid_height_mm);
        put_be(out + 22, 1, 0xFFu, s->spare_host_config__static_config_spare_0);
        put_be(out + 23, 1, 0xFFu, s->spare_host_config__static_config_spare_1);
        put_be(out + 24, 2, 0xFFFFu, s->algo__range_ignore_threshold_mcps);
        put_be(out + 26, 1, 0xFFu, s->algo__range_ignore_valid_height_mm);
        put_be(out + 27, 1, 0xFFu, s->algo__range_min_clip);
        put_be(out + 28, 1, 0xFu, s->algo__consistency_check__tolerance);
        put_be(out + 29, 1, 0xFFu, s->spare_host_config__static_config_spare_2);
        put_be(out + 30, 1, 0xFu, s->sd_config__reset_stages_msb);
        put_be(out + 31, 1, 0xFFu, s->sd_config__reset_stages_lsb);
        break;
    }
    case VLXB_BLK_GENERAL_CONFIG: {
        const vlxb_general_config *s = &img->general_config;
        memcpy(out, s->raw, 22);
        put_be(out + 0, 1, 0xFFu, s->gph_config__stream_count_update_value);
        put_be(out + 1, 1, 0xFFu, s->global_config__stream_divider);
        put_be(out + 2, 1, 0xFFu, s->system__interrupt_config_gpio);
        put_be(out + 3, 1, 0x7Fu, s->cal_config__vcsel_start);
        put_be(out + 4, 2, 0xFFFu, s->cal_config__repeat_rate);
        put_be(out + 6, 1, 0x7Fu, s->global_config__vcsel_width);
        put_be(out + 7, 1, 0xFFu, s->phasecal_config__timeout_macrop);
        put_be(out + 8, 1, 0xFFu, s->phasecal_config__target);
        put_be(out + 9, 1, 0x1u, s->phasecal_config__override);
        put_be(out + 11, 1, 0x7u, s->dss_config__roi_mode_control);
        put_be(out + 12, 2, 0xFFFFu, s->system__thresh_rate_high);
        put_be(out + 14, 2, 0xFFFFu, s->system__thresh_rate_low);
        put_be(out + 16, 2, 0xFFFFu, s->dss_config__manual_effective_spads_select);
        put_be(out + 18, 1, 0xFFu, s->dss_config__manual_block_select);
        put_be(out + 19, 1, 0xFFu, s->dss_config__aperture_attenuation);
        put_be(out + 20, 1, 0xFFu, s->dss_config__max_spads_limit);
        put_be(out + 21, 1, 0xFFu, s->dss_config__min_spads_limit);
        break;
    }
    case VLXB_BLK_TIMING_CONFIG: {
        const vlxb_timing_config *s = &img->timing_config;
        memcpy(out, s->raw, 23);
        put_be(out + 0, 1, 0xFu, s->mm_config__timeout_macrop_a_hi);
        put_be(out + 1, 1, 0xFFu, s->mm_config__timeout_macrop_a_lo);
        put_be(out + 2, 1, 0xFu, s->mm_config__timeout_macrop_b_hi);
        put_be(out + 3, 1, 0xFFu, s->mm_config__timeout_macrop_b_lo);
        put_be(out + 4, 1, 0xFu, s->range_config__timeout_macrop_a_hi);
        put_be(out + 5, 1, 0xFFu, s->range_config__timeout_macrop_a_lo);
        put_be(out + 6, 1, 0x3Fu, s->range_config__vcsel_period_a);
        put_be(out + 7, 1, 0xFu, s->range_config__timeout_macrop_b_hi);
        put_be(out + 8, 1, 0xFFu, s->range_config__timeout_macrop_b_lo);
        put_be(out + 9, 1, 0x3Fu, s->range_config__vcsel_period_b);
        put_be(out + 10, 2, 0xFFFFu, s->range_config__sigma_thresh);
        put_be(out + 12, 2, 0xFFFFu, s->range_config__min_count_rate_rtn_limit_mcps);
        put_be(out + 14, 1, 0xFFu, s->range_config__valid_phase_low);
        put_be(out + 15, 1, 0xFFu, s->range_config__valid_phase_high);
        put_be(out + 18, 4, 0xFFFFFFFFu, s->system__intermeasurement_period);
        put_be(out + 22, 1, 0x1u, s->system__fractional_enable);
        break;
    }
    case VLXB_BLK_DYNAMIC_CONFIG: {
        const vlxb_dynamic_config *s = &img->dynamic_config;
        memcpy(out, s->raw, 18);
        put_be(out + 0, 1, 0x3u, s->system__grouped_parameter_hold_0);
        put_be(out + 1, 2, 0xFFFFu, s->system__thresh_high);
        put_be(out + 3, 2, 0xFFFFu, s->system__thresh_low);
        put_be(out + 5, 1, 0x1u, s->system__enable_xtalk_per_quadrant);
        put_be(out + 6, 1, 0x7u, s->system__seed_config);
        put_be(out + 7, 1, 0xFFu, s->sd_config__woi_sd0);
        put_be(out + 8, 1, 0xFFu, s->sd_config__woi_sd1);
        put_be(out + 9, 1, 0x7Fu, s->sd_config__initial_phase_sd0);
        put_be(out + 10, 1, 0x7Fu, s->sd_config__initial_phase_sd1);
        put_be(out + 11, 1, 0x3u, s->system__grouped_parameter_hold_1);
        put_be(out + 12, 1, 0x3u, s->sd_config__first_order_select);
        put_be(out + 13, 1, 0xFu, s->sd_config__quantifier);
        put_be(out + 14, 1, 0xFFu, s->roi_config__user_roi_centre_spad);
        put_be(out + 15, 1, 0xFFu, s->roi_config__user_roi_requested_global_xy_size);
        put_be(out + 16, 1, 0xFFu, s->system__sequence_config);
        put_be(out + 17, 1, 0x3u, s->system__grouped_parameter_hold);
        break;
    }
    case VLXB_BLK_SYSTEM_CONTROL: {
        const vlxb_system_control *s = &img->system_control;
        memcpy(out, s->raw, 5);
        put_be(out + 0, 1, 0x1u, s->power_management__go1_power_force);
        put_be(out + 1, 1, 0x1u, s->system__stream_count_ctrl);
        put_be(out + 2, 1, 0x1u, s->firmware__enable);
        put_be(out + 3, 1, 0x3u, s->system__interrupt_clear);
        put_be(out + 4, 1, 0xFFu, s->system__mode_start);
        break;
    }
    case VLXB_BLK_SYSTEM_RESULTS: {
        const vlxb_system_results *s = &img->system_results;
        memcpy(out, s->raw, 44);
        put_be(out + 0, 1, 0x3Fu, s->result__interrupt_status);
        put_be(out + 1, 1, 0xFFu, s->result__range_status);
        put_be(out + 2, 1, 0xFu, s->result__report_status);
        put_be(out + 3, 1, 0xFFu, s->result__stream_count);
        put_be(out + 4, 2, 0xFFFFu, s->result__dss_actual_effective_spads_sd0);
        put_be(out + 6, 2, 0xFFFFu, s->result__peak_signal_count_rate_mcps_sd0);
        put_be(out + 8, 2, 0xFFFFu, s->result__ambient_count_rate_mcps_sd0);
        put_be(out + 10, 2, 0xFFFFu, s->result__sigma_sd0);
        put_be(out + 12, 2, 0xFFFFu, s->result__phase_sd0);
        put_be(out + 14, 2, 0xFFFFu, s->result__final_crosstalk_corrected_range_mm_sd0);
        put_be(out + 16, 2, 0xFFFFu, s->result__peak_signal_count_rate_crosstalk_corrected_mcps_sd0);
        put_be(out + 18, 2, 0xFFFFu, s->result__mm_inner_actual_effective_spads_sd0);
        put_be(out + 20, 2, 0xFFFFu, s->result__mm_outer_actual_effective_spads_sd0);
        put_be(out + 22, 2, 0xFFFFu, s->result__avg_signal_count_rate_mcps_sd0);
        put_be(out + 24, 2, 0xFFFFu, s->result__dss_actual_effective_spads_sd1);
        put_be(out + 26, 2, 0xFFFFu, s->result__peak_signal_count_rate_mcps_sd1);
        put_be(out + 28, 2, 0xFFFFu, s->result__ambient_count_rate_mcps_sd1);
        put_be(out + 30, 2, 0xFFFFu, s->result__sigma_sd1);
        put_be(out + 32, 2, 0xFFFFu, s->result__phase_sd1);
        put_be(out + 34, 2, 0xFFFFu, s->result__final_crosstalk_corrected_range_mm_sd1);
        put_be(out + 36, 2, 0xFFFFu, s->result__spare_0_sd1);
        put_be(out + 38, 2, 0xFFFFu, s->result__spare_1_sd1);
        put_be(out + 40, 2, 0xFFFFu, s->result__spare_2_sd1);
        put_be(out + 42, 1, 0xFFu, s->result__spare_3_sd1);
        put_be(out + 43, 1, 0xFFu, s->result__thresh_info);
        break;
    }
    case VLXB_BLK_CORE_RESULTS: {
        const vlxb_core_results *s = &img->core_results;
        memcpy(out, s->raw, 33);
        put_be(out + 0, 4, 0xFFFFFFFFu, s->result_core__ambient_window_events_sd0);
        put_be(out + 4, 4, 0xFFFFFFFFu, s->result_core__ranging_total_events_sd0);
        put_be(out + 8, 4, 0xFFFFFFFFu, s->result_core__signal_total_events_sd0);
        put_be(out + 12, 4, 0xFFFFFFFFu, s->result_core__total_periods_elapsed_sd0);
        put_be(out + 16, 4, 0xFFFFFFFFu, s->result_core__ambient_window_events_sd1);
        put_be(out + 20, 4, 0xFFFFFFFFu, s->result_core__ranging_total_events_sd1);
        put_be(out + 24, 4, 0xFFFFFFFFu, s->result_core__signal_total_events_sd1);
        put_be(out + 28, 4, 0xFFFFFFFFu, s->result_core__total_periods_elapsed_sd1);
        put_be(out + 32, 1, 0xFFu, s->result_core__spare_0);
        break;
    }
    case VLXB_BLK_DEBUG_RESULTS: {
        const vlxb_debug_results *s = &img->debug_results;
        memcpy(out, s->raw, 56);
        put_be(out + 0, 2, 0xFFFFu, s->phasecal_result__reference_phase);
        put_be(out + 2, 1, 0x7Fu, s->phasecal_result__vcsel_start);
        put_be(out + 3, 1, 0x3Fu, s->ref_spad_char_result__num_actual_ref_spads);
        put_be(out + 4, 1, 0x3u, s->ref_spad_char_result__ref_location);
        put_be(out + 5, 1, 0x1u, s->vhv_result__coldboot_status);
        put_be(out + 6, 1, 0x3Fu, s->vhv_result__search_result);
        put_be(out + 7, 1, 0x3Fu, s->vhv_result__latest_setting);
        put_be(out + 8, 2, 0x3FFu, s->result__osc_calibrate_val);
        put_be(out + 10, 1, 0x3u, s->ana_config__powerdown_go1);
        put_be(out + 11, 1, 0x3u, s->ana_config__ref_bg_ctrl);
        put_be(out + 12, 1, 0xFu, s->ana_config__regdvdd1v2_ctrl);
        put_be(out + 13, 1, 0x7u, s->ana_config__osc_slow_ctrl);
        put_be(out + 14, 1, 0x1u, s->test_mode__status);
        put_be(out + 15, 1, 0x3u, s->firmware__system_status);
        put_be(out + 16, 1, 0xFFu, s->firmware__mode_status);
        put_be(out + 17, 1, 0xFFu, s->firmware__secondary_mode_status);
        put_be(out + 18, 2, 0xFFFu, s->firmware__cal_repeat_rate_counter);
        put_be(out + 22, 2, 0xFFFFu, s->gph__system__thresh_high);
        put_be(out + 24, 2, 0xFFFFu, s->gph__system__thresh_low);
        put_be(out + 26, 1, 0x1u, s->gph__system__enable_xtalk_per_quadrant);
        put_be(out + 27, 1, 0x7u, s->gph__spare_0);
        put_be(out + 28, 1, 0xFFu, s->gph__sd_config__woi_sd0);
        put_be(out + 29, 1, 0xFFu, s->gph__sd_config__woi_sd1);
        put_be(out + 30, 1, 0x7Fu, s->gph__sd_config__initial_phase_sd0);
        put_be(out + 31, 1, 0x7Fu, s->gph__sd_config__initial_phase_sd1);
        put_be(out + 32, 1, 0x3u, s->gph__sd_config__first_order_select);
        put_be(out + 33, 1, 0xFu, s->gph__sd_config__quantifier);
        put_be(out + 34, 1, 0xFFu, s->gph__roi_config__user_roi_centre_spad);
        put_be(out + 35, 1, 0xFFu, s->gph__roi_config__user_roi_requested_global_xy_size);
        put_be(out + 36, 1, 0xFFu, s->gph__system__sequence_config);
        put_be(out + 37, 1, 0x1u, s->gph__gph_id);
        put_be(out + 38, 1, 0x3u, s->system__interrupt_set);
        put_be(out + 39, 1, 0x1Fu, s->interrupt_manager__enables);
        put_be(out + 40, 1, 0x1Fu, s->interrupt_manager__clear);
        put_be(out + 41, 1, 0x1Fu, s->interrupt_manager__status);
        put_be(out + 42, 1, 0x1u, s->mcu_to_host_bank__wr_access_en);
        put_be(out + 43, 1, 0x1u, s->power_management__go1_reset_status);
        put_be(out + 44, 1, 0x3u, s->pad_startup_mode__value_ro);
        put_be(out + 45, 1, 0x3Fu, s->pad_startup_mode__value_ctrl);
        put_be(out + 46, 4, 0x3FFFFu, s->pll_period_us);
        put_be(out + 50, 4, 0xFFFFFFFFu, s->interrupt_scheduler__data_out);
        put_be(out + 54, 1, 0x1u, s->nvm_bist__complete);
        put_be(out + 55, 1, 0x1u, s->nvm_bist__status);
        break;
    }
    case VLXB_BLK_NVM_COPY_DATA: {
        const vlxb_nvm_copy_data *s = &img->nvm_copy_data;
        memcpy(out, s->raw, 49);
        put_be(out + 0, 1, 0xFFu, s->identification__model_id);
        put_be(out + 1, 1, 0xFFu, s->identification__module_type);
        put_be(out + 2, 1, 0xFFu, s->identification__revision_id);
        put_be(out + 3, 2, 0xFFFFu, s->identification__module_id);
        put_be(out + 5, 1, 0x7Fu, s->ana_config__fast_osc__trim_max);
        put_be(out + 6, 1, 0x7u, s->ana_config__fast_osc__freq_set);
        put_be(out + 7, 1, 0x7u, s->ana_config__vcsel_trim);
        put_be(out + 8, 1, 0x3Fu, s->ana_config__vcsel_selion);
        put_be(out + 9, 1, 0x3Fu, s->ana_config__vcsel_selion_max);
        put_be(out + 10, 1, 0x1u, s->protected_laser_safety__lock_bit);
        put_be(out + 11, 1, 0x7Fu, s->laser_safety__key);
        put_be(out + 12, 1, 0x1u, s->laser_safety__key_ro);
        put_be(out + 13, 1, 0x3Fu, s->laser_safety__clip);
        put_be(out + 14, 1, 0x3Fu, s->laser_safety__mult);
        put_be(out + 15, 1, 0xFFu, s->global_config__spad_enables_rtn_0);
        put_be(out + 16, 1, 0xFFu, s->global_config__spad_enables_rtn_1);
        put_be(out + 17, 1, 0xFFu, s->global_config__spad_enables_rtn_2);
        put_be(out + 18, 1, 0xFFu, s->global_config__spad_enables_rtn_3);
        put_be(out + 19, 1, 0xFFu, s->global_config__spad_enables_rtn_4);
        put_be(out + 20, 1, 0xFFu, s->global_config__spad_enables_rtn_5);
        put_be(out + 21, 1, 0xFFu, s->global_config__spad_enables_rtn_6);
        put_be(out + 22, 1, 0xFFu, s->global_config__spad_enables_rtn_7);
        put_be(out + 23, 1, 0xFFu, s->global_config__spad_enables_rtn_8);
        put_be(out + 24, 1, 0xFFu, s->global_config__spad_enables_rtn_9);
        put_be(out + 25, 1, 0xFFu, s->global_config__spad_enables_rtn_10);
        put_be(out + 26, 1, 0xFFu, s->global_config__spad_enables_rtn_11);
        put_be(out + 27, 1, 0xFFu, s->global_config__spad_enables_rtn_12);
        put_be(out + 28, 1, 0xFFu, s->global_config__spad_enables_rtn_13);
        put_be(out + 29, 1, 0xFFu, s->global_config__spad_enables_rtn_14);
        put_be(out + 30, 1, 0xFFu, s->global_config__spad_enables_rtn_15);
        put_be(out + 31, 1, 0xFFu, s->global_config__spad_enables_rtn_16);
        put_be(out + 32, 1, 0xFFu, s->global_config__spad_enables_rtn_17);
        put_be(out + 33, 1, 0xFFu, s->global_config__spad_enables_rtn_18);
        put_be(out + 34, 1, 0xFFu, s->global_config__spad_enables_rtn_19);
        put_be(out + 35, 1, 0xFFu, s->global_config__spad_enables_rtn_20);
        put_be(out + 36, 1, 0xFFu, s->global_config__spad_enables_rtn_21);
        put_be(out + 37, 1, 0xFFu, s->global_config__spad_enables_rtn_22);
        put_be(out + 38, 1, 0xFFu, s->global_config__spad_enables_rtn_23);
        put_be(out + 39, 1, 0xFFu, s->global_config__spad_enables_rtn_24);
        put_be(out + 40, 1, 0xFFu, s->global_config__spad_enables_rtn_25);
        put_be(out + 41, 1, 0xFFu, s->global_config__spad_enables_rtn_26);
        put_be(out + 42, 1, 0xFFu, s->global_config__spad_enables_rtn_27);
        put_be(out + 43, 1, 0xFFu, s->global_config__spad_enables_rtn_28);
        put_be(out + 44, 1, 0xFFu, s->global_config__spad_enables_rtn_29);
        put_be(out + 45, 1, 0xFFu, s->global_config__spad_enables_rtn_30);
        put_be(out + 46, 1, 0xFFu, s->global_config__spad_enables_rtn_31);
        put_be(out + 47, 1, 0xFFu, s->roi_config__mode_roi_centre_spad);
        put_be(out + 48, 1, 0xFFu, s->roi_config__mode_roi_xy_size);
        break;
    }
    case VLXB_BLK_PATCH_DEBUG: {
        const vlxb_patch_debug *s = &img->patch_debug;
        memcpy(out, s->raw, 2);
        put_be(out + 0, 1, 0xFFu, s->result__debug_status);
        put_be(out + 1, 1, 0xFFu, s->result__debug_stage);
        break;
    }
    case VLXB_BLK_GPH_GENERAL_CONFIG: {
        const vlxb_gph_general_config *s = &img->gph_general_config;
        memcpy(out, s->raw, 5);
        put_be(out + 0, 2, 0xFFFFu, s->gph__system__thresh_rate_high);
        put_be(out + 2, 2, 0xFFFFu, s->gph__system__thresh_rate_low);
        put_be(out + 4, 1, 0xFFu, s->gph__system__interrupt_config_gpio);
        break;
    }
    case VLXB_BLK_GPH_STATIC_CONFIG: {
        const vlxb_gph_static_config *s = &img->gph_static_config;
        memcpy(out, s->raw, 6);
        put_be(out + 0, 1, 0x7u, s->gph__dss_config__roi_mode_control);
        put_be(out + 1, 2, 0xFFFFu, s->gph__dss_config__manual_effective_spads_select);
        put_be(out + 3, 1, 0xFFu, s->gph__dss_config__manual_block_select);
        put_be(out + 4, 1, 0xFFu, s->gph__dss_config__max_spads_limit);
        put_be(out + 5, 1, 0xFFu, s->gph__dss_config__min_spads_limit);
        break;
    }
    case VLXB_BLK_GPH_TIMING_CONFIG: {
        const vlxb_gph_timing_config *s = &img->gph_timing_config;
        memcpy(out, s->raw, 16);
        put_be(out + 0, 1, 0xFu, s->gph__mm_config__timeout_macrop_a_hi);
        put_be(out + 1, 1, 0xFFu, s->gph__mm_config__timeout_macrop_a_lo);
        put_be(out + 2, 1, 0xFu, s->gph__mm_config__timeout_macrop_b_hi);
        put_be(out + 3, 1, 0xFFu, s->gph__mm_config__timeout_macrop_b_lo);
        put_be(out + 4, 1, 0xFu, s->gph__range_config__timeout_macrop_a_hi);
        put_be(out + 5, 1, 0xFFu, s->gph__range_config__timeout_macrop_a_lo);
        put_be(out + 6, 1, 0x3Fu, s->gph__range_config__vcsel_period_a);
        put_be(out + 7, 1, 0x3Fu, s->gph__range_config__vcsel_period_b);
        put_be(out + 8, 1, 0xFu, s->gph__range_config__timeout_macrop_b_hi);
        put_be(out + 9, 1, 0xFFu, s->gph__range_config__timeout_macrop_b_lo);
        put_be(out + 10, 2, 0xFFFFu, s->gph__range_config__sigma_thresh);
        put_be(out + 12, 2, 0xFFFFu, s->gph__range_config__min_count_rate_rtn_limit_mcps);
        put_be(out + 14, 1, 0xFFu, s->gph__range_config__valid_phase_low);
        put_be(out + 15, 1, 0xFFu, s->gph__range_config__valid_phase_high);
        break;
    }
    case VLXB_BLK_FW_INTERNAL: {
        const vlxb_fw_internal *s = &img->fw_internal;
        memcpy(out, s->raw, 2);
        put_be(out + 0, 1, 0xFFu, s->firmware__internal_stream_count_div);
        put_be(out + 1, 1, 0xFFu, s->firmware__internal_stream_counter_val);
        break;
    }
    default:
        break;
    }
}
